"""V_eta #61 -- the stimulus response family, schema side.

STATUS: WRITTEN AND RUN 2026-08-10 -- 19 passed against the built V_eta set,
inside the full suite of 1098. This file is Python and this container has one;
the MATLAB half of #61 (both migrators and both test files under
DID-matlab/tests/+did2/+unittest/) has NEVER been executed, because there is no
MATLAB here. Nothing in this file proves anything about the migrators.

Guards the SIGNED model (`schemas/V_eta_stimulus_response_model_plan.md`,
TEAM-SIGN-OFF [stimulus response], jess@walthamdatascience.com / 2026-08-08):
four v1 classes collapse to TWO -- `harmonic_component` (an abstract `data_type`
composite) plus `harmonic_component_calculation` (its `subject_calculation`
leaf, id preserved) -- and four source tombstones are repaired on the way.

WHY A SEPARATE FILE, AND WHAT IT IS ANCHORED TO
-----------------------------------------------
Every assertion about did_v1 in here reads `schemas/V_eta_ndi_ground_truth.json`
(generated by `tools/ndi_ground_truth.py` from NDI `origin/main`) rather than
restating what the V_eta schema says. That is the point: this family's whole
defect history was V_eta schemas written against DID-schema's own V_alpha
snapshot, so a test that compares V_eta to V_eta would have passed throughout.
The largest single instance of the invented-empty-edge pattern lived here --
`stimulus_response_scalar_parameters_basic.stimulus_response_scalar_id`,
REQUIRED, and empty on 11,440 of 11,440 corpus documents.

DENOMINATOR NOTE: each test that counts states what it counted.
"""
import glob
import json
import os

import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VETA = os.path.join(REPO_ROOT, "schemas", "V_eta")
GROUND_TRUTH = os.path.join(REPO_ROOT, "schemas", "V_eta_ndi_ground_truth.json")

FAMILY = (
    "stimulus_response",
    "stimulus_response_scalar",
    "stimulus_response_scalar_parameters",
    "stimulus_response_scalar_parameters_basic",
)


def _built():
    """class_name -> (tier, schema dict) for every built V_eta schema."""
    out = {}
    for path in sorted(glob.glob(os.path.join(VETA, "*", "*.json"))):
        with open(path) as fh:
            d = json.load(fh)
        if "document_class" not in d:
            continue  # the meta/registry sidecars
        out[d["document_class"]["class_name"]] = (
            os.path.basename(os.path.dirname(path)),
            d,
        )
    return out


BUILT = _built()

with open(GROUND_TRUTH) as _fh:
    NDI = json.load(_fh)["classes"]


def _dep_names(schema):
    return {d["name"] for d in schema.get("depends_on", [])}


def _field(schema, name):
    for f in schema.get("fields", []):
        if f["name"] == name:
            return f
    raise AssertionError(
        "%s has no field %r; it has %r"
        % (schema["document_class"]["class_name"], name,
           [f["name"] for f in schema.get("fields", [])])
    )


# ---------------------------------------------------------------- the targets

def test_harmonic_component_is_an_abstract_data_type_composite():
    """The composite half of the signed pair. ABSTRACT: a bare harmonic is never
    a document, only the direction leaf is."""
    tier, d = BUILT["harmonic_component"]
    assert tier == "draft"
    assert d["document_class"].get("abstract") is True
    assert [s["class_name"] for s in d["document_class"]["superclasses"]] == ["data_type"]
    # T14: ONE `value` slot, structure, not a bag of loose top-level fields.
    assert [f["name"] for f in d["fields"]] == ["value"]
    assert d["fields"][0]["type"] == "structure"


def test_the_value_cell_carries_the_five_signed_subfields():
    """As signed: {harmonic (0=DC, 1=F1, 2=F2), real, imaginary, control_real,
    control_imaginary}. The CONTROL pair is the half V_eta previously had no home
    for at all -- `control_response_real[]` is meaningless without it."""
    _tier, d = BUILT["harmonic_component"]
    subs = {s["name"]: s for s in _field(d, "value")["fields"]}
    assert set(subs) == {"harmonic", "real", "imaginary",
                         "control_real", "control_imaginary"}


def test_the_four_coefficient_subfields_are_matrices_and_harmonic_is_scalar():
    """One coefficient PER READING, not one per document. The writer fills these
    from a column -- one row per stimulus presentation
    (tuning_response.m:309-313) -- so a real document carries as many
    coefficients as it has readings.

    This was built as scalar `double` and corrected 2026-08-10. It had not bitten
    because +did2/+schema/cache.m validates a block's TOP-LEVEL fields and never
    recurses into a structure's sub-fields, so a wrong sub-field type is
    unenforced today; it would have surfaced the moment sub-field validation
    landed, against documents already written in the wrong shape.

    `harmonic` stays scalar: there is exactly one harmonic number per component,
    which is what makes the component a component."""
    _tier, d = BUILT["harmonic_component"]
    subs = {s["name"]: s for s in _field(d, "value")["fields"]}
    for name in ("real", "imaginary", "control_real", "control_imaginary"):
        assert subs[name]["type"] == "matrix", name
        assert subs[name]["mustBeScalar"] is False, name
    assert subs["harmonic"]["type"] == "integer"
    assert subs["harmonic"]["mustBeScalar"] is True


def test_harmonic_component_calculation_is_the_subject_calculation_leaf():
    """Mirrors tuning_curve / tuning_curve_calculation exactly. The tier is
    `subject_calculation` because this is computed, and because
    `stimulus_tuningcurve` -- the other output of the same app and the same file
    -- already folds to a calculation leaf. Treating two outputs of one app
    differently would be drift by our own definition."""
    _tier, d = BUILT["harmonic_component_calculation"]
    assert [s["class_name"] for s in d["document_class"]["superclasses"]] == [
        "subject_calculation", "harmonic_component"]
    assert d["document_class"].get("abstract") is not True
    # It declares NO edges of its own: subject_id / time_reference_# /
    # instrument_id / software_id / method_parameters_id / derived_from_# all
    # arrive from the subject_statement -> subject_interaction -> subject_calculation
    # chain. Re-declaring any of them here is the duplicate-declaration defect.
    assert d.get("depends_on", []) == []


def test_the_leaf_inherits_every_edge_the_fold_writes():
    """The migrator writes subject_id, time_reference_1, instrument_id,
    derived_from_1, derived_from_2 and method_parameters_id. Each must be
    declared SOMEWHERE in the ancestor chain, or the fold is writing edges the
    schema does not know about."""
    chain = ["subject_statement", "subject_interaction", "subject_calculation"]
    declared = set()
    for cls in chain:
        declared |= _dep_names(BUILT[cls][1])
    assert {"subject_id", "time_reference_#", "instrument_id",
            "method_parameters_id", "derived_from_#"} <= declared
    # derived_from_# is a FAMILY, so the fold may name derived_from_1 AND _2.
    # #63 has not put a maximum on it; assert there is none, so a future cap
    # cannot land silently under a fold that emits two.
    dfrom = next(d for d in BUILT["subject_calculation"][1]["depends_on"]
                 if d["name"] == "derived_from_#")
    assert "max_count" not in dfrom or dfrom["max_count"] is None


# ------------------------------------------------- the source tombstones (v1)

def test_all_four_source_tombstones_survive_the_build():
    """NOT phase-8 deleted, and that is load-bearing rather than incidental.

    Both migrators fall back to a guarded PASSTHROUGH -- the response when it has
    no element_id / no parseable response_type / no values, and the parameters
    document always, because the inline fold needs the resolver pass. A
    passthrough of a phase-8-deleted class has no schema to validate against and
    quarantines every document; that is exactly what put 2,484 corpus-B
    documents in quarantine when the epoch family landed.

    The signed plan does say stimulus_response and
    stimulus_response_scalar_parameters are DELETE. They cannot go yet: both are
    SUPERCLASSES of the two classes that still pass through, and
    `stimulus_response` additionally owns the block that carries
    `element_epochid`/`stimulator_epochid` on a passed-through response."""
    for cls in FAMILY:
        assert cls in BUILT, "%s was deleted; a passthrough would quarantine" % cls


def test_no_tombstone_field_is_invented_relative_to_the_ndi_template():
    """The ground-truth rule, mechanically. DENOMINATOR: 4 classes."""
    checked = 0
    for cls in FAMILY:
        _tier, d = BUILT[cls]
        ours = {f["name"] for f in d.get("fields", [])}
        theirs = set(NDI[cls]["fields"])
        assert ours <= theirs, "%s declares fields NDI has not: %r" % (
            cls, sorted(ours - theirs))
        checked += 1
    assert checked == 4


def test_no_tombstone_drops_a_field_the_ndi_template_declares():
    """The other direction -- a dropped field silently truncates a passthrough
    document into a fragment. DENOMINATOR: 4 classes."""
    for cls in FAMILY:
        _tier, d = BUILT[cls]
        ours = {f["name"] for f in d.get("fields", [])}
        theirs = set(NDI[cls]["fields"])
        assert theirs <= ours, "%s is missing NDI fields: %r" % (
            cls, sorted(theirs - ours))


def test_response_file_is_not_declared_anywhere_in_the_family():
    """REPAIR 3. `stimulus_response` used to declare a `response_file`. No NDI
    template in this family has a file at all -- invented."""
    for cls in FAMILY:
        _tier, d = BUILT[cls]
        assert NDI[cls]["files"] == []
        assert d.get("file", []) == []
        assert "response_file" not in {f["name"] for f in d.get("fields", [])}


def test_every_edge_in_the_family_matches_the_ndi_template_exactly():
    """THE REPAIR THIS FAMILY EXISTS FOR. V_eta had the parameters edge REVERSED
    -- it required the parameters document to point at the response, while NDI
    writes the response pointing at its parameters -- and had dropped
    `stimulator_id` and `stimulus_control_id` entirely.

    DENOMINATOR: 4 classes, 5 NDI edges in total across them."""
    total = 0
    for cls in FAMILY:
        _tier, d = BUILT[cls]
        assert _dep_names(d) == set(NDI[cls]["depends_on"]), cls
        total += len(NDI[cls]["depends_on"])
    assert total == 5


def test_the_largest_invented_empty_edge_instance_stays_dead():
    """`stimulus_response_scalar_parameters_basic.stimulus_response_scalar_id`:
    REQUIRED, invented, pointed the wrong way, and empty on 11,440 of 11,440
    documents (Soph 11,167 / 20211116 273) -- every one of which validated clean,
    because +did2/+validate/references.m:90 skips empty edges.

    NDI declares NO depends_on on either parameters class. Named explicitly, not
    just covered by the sweep above, because this is the row the whole #37
    pattern was measured from."""
    for cls in ("stimulus_response_scalar_parameters",
                "stimulus_response_scalar_parameters_basic"):
        assert NDI[cls]["depends_on"] == []
        assert BUILT[cls][1].get("depends_on", []) == []


def test_the_response_points_at_its_parameters_and_not_the_reverse():
    _tier, d = BUILT["stimulus_response_scalar"]
    assert _dep_names(d) == {"stimulus_response_scalar_parameters_id"}
    # `stimulus_response_id` was the same invention one class down: a name no
    # did_v1 document carries.
    assert "stimulus_response_id" not in _dep_names(d)


def test_the_two_recovered_edges_are_declared_and_required():
    """`stimulator_id` is not merely lost data -- it is a LIVE QUERY
    (`ndi.query('','depends_on','stimulator_id', p.id())` in
    stimulusResponse.m's responseQuery). `stimulus_control_id` is what
    `control_response_real[]` is measured against. NDI's schema marks all four
    "mustbenotempty": 1 and one writer sets all five together, which is the
    positive evidence CLAUDE.md demands before declaring a required edge."""
    _tier, d = BUILT["stimulus_response"]
    deps = {x["name"]: x for x in d["depends_on"]}
    assert set(deps) == {"element_id", "stimulator_id",
                         "stimulus_presentation_id", "stimulus_control_id"}
    assert all(x["mustBeNonEmpty"] for x in deps.values())


# ------------------------------------------------------------------- repair 4

def test_freq_response_is_a_harmonic_number_not_a_boolean():
    """REPAIR 4 of the signed plan, and the last one of the five to be built.

    The field was `integer {min: 0, max: 1}`, documented "1 if this scalar
    response is a frequency-domain measurement, 0 otherwise". It is the HARMONIC
    INDEX. tuning_response.m:202 sweeps `freq_response_commands = [0 1 2]` by
    default, :260 assigns one per document and :262-266 turns it into
    'mean' | 'F1' | 'F2' -- so `max: 1` is a claim that would reject roughly a
    third of the class.

    TWO errors, and the second is why nothing broke: `+did2/+schema/cache.m`
    validateConstraints (:1340) switches on
    maxLength|minLength|minimum|maximum|enum and silently tolerates anything
    else, so `min`/`max` were INERT and never enforced. Fixing only the spelling
    would have quarantined every F2 document."""
    _tier, d = BUILT["stimulus_response_scalar_parameters_basic"]
    f = _field(d, "freq_response")
    c = f.get("constraints") or {}
    assert "max" not in c and "min" not in c, "the inert spelling is back: %r" % c
    assert c.get("minimum") == 0
    # NO maximum. :207 is `freq_response_commands = freq_response`, straight from
    # the caller, so 3 is representable; a bound we cannot derive from the writer
    # is the invention this repair track exists to remove.
    assert "maximum" not in c
    assert "0 otherwise" not in f["documentation"]
    assert "harmonic" in f["documentation"].lower()


def test_isspike_is_left_alone_and_the_inert_spelling_is_counted():
    """DENOMINATOR: 241 built schema files walked (4 meta sidecars skipped).

    `isspike` is equally inert but its INTENT is correct -- the writer sets 0 or
    1 and nothing else (:176, :179-182) -- so rewriting its key would newly
    ENFORCE a rule on 11,440 live documents to no benefit. Pinned so the count
    of inert declarations is a number somebody chose, not one nobody noticed."""
    inert = []
    walked = 0

    def walk(fields, cls, prefix):
        for f in fields:
            c = f.get("constraints") or {}
            if "min" in c or "max" in c:
                inert.append("%s.%s%s" % (cls, prefix, f["name"]))
            if f.get("fields"):
                walk(f["fields"], cls, prefix + f["name"] + ".")

    for path in sorted(glob.glob(os.path.join(VETA, "*", "*.json"))):
        with open(path) as fh:
            d = json.load(fh)
        if "document_class" not in d:
            continue
        walked += 1
        walk(d.get("fields", []), d["document_class"]["class_name"], "")

    assert walked == 241, "schema count moved; re-derive the inert set (%d)" % walked
    assert sorted(inert) == [
        "element.direct",
        "element.reference",
        "stimulus_response_scalar_parameters_basic.isspike",
    ]


# --------------------------------------------------------- deferrals, recorded

@pytest.mark.parametrize("cls", ["harmonic_component", "harmonic_component_calculation"])
def test_the_new_pair_stays_in_draft_until_the_resolver_lands(cls):
    """Both halves of the fold are DRAFT on purpose. The signed model is not
    fully built: the parameters are still a separate document (the inline fold
    needs the resolver pass), `responses.stimid` has no `axes[]` to land on
    (#45), and `element_epochid` has no `epoch` document to anchor to (#45/#67).
    Promoting either class to stable would assert a completeness that does not
    exist."""
    assert BUILT[cls][0] == "draft"


def test_subject_statement_still_has_no_axes_so_stimid_deferral_is_real():
    """Revision 1 of the signed plan moves `responses.stimid` from `conditions`
    to an `axes[]` entry, because `conditions` tightened to cardinality EXACTLY 1
    and is explicitly NOT an axis. Neither half exists yet.

    WHEN #45 LANDS THIS TEST MUST BE INVERTED, not patched -- it asserts the
    absence that justifies the migrator carrying neither field."""
    _tier, d = BUILT["subject_statement"]
    names = {f["name"] for f in d["fields"]}
    assert "axes" not in names
    assert names == {"variable", "conditions", "storage_mode"}


def test_relative_reference_still_requires_a_referent_no_migrator_can_mint():
    """Revision 2 anchors `element_epochid` as a `relative_reference` whose
    `relative_to` points at an `epoch` document. `relative_to` is mustBeNonEmpty,
    so emitting one in pass 1 would write an empty required edge -- a husk that
    +did2/+validate/references.m:90 skips and no gate catches.

    NOTE WHAT THE BLOCKER IS NOT. The `epoch` CLASS exists (V_eta/stable). An
    earlier draft of this test asserted it did not, and was wrong: class
    existence was never the gate. The gate is that an epoch DOCUMENT has to be
    MINTED, one per epoch, and `epoch.session_id` is itself mustBeNonEmpty and
    must refer to a `session` document whose base.id is a fresh uid rather than
    the `base.session_id` every other document carries. Both are corpus-wide
    groupings; a single-document migrator sees one document. The DID-matlab side
    records the same conclusion from the other direction --
    `+migrators_j/private/jEpochDocId.m:31` carries the grep that shows no
    migrator constructs an `epoch`.

    WHEN THE EPOCH MINT LANDS THIS TEST MUST BE INVERTED, not patched."""
    _tier, d = BUILT["relative_reference"]
    rel = next(x for x in d["depends_on"] if x["name"] == "relative_to")
    assert rel["mustBeNonEmpty"] is True
    epoch = BUILT["epoch"][1]
    sess = next(x for x in epoch["depends_on"] if x["name"] == "session_id")
    assert sess["mustBeNonEmpty"] is True
