"""Dissolution must be SAID, a recorded target must not vanish, and build state
is two halves.

WHY THIS FILE EXISTS
--------------------
`tools/coverage.py` used to render, for any row whose target list happened to
be empty:

    · **will dissolve / be deleted** (no target by design)

produced by `if dt else` -- a settled-sounding conclusion generated by an empty
list. Seven rows carried it. It was wrong for `filter` (whose signed model makes
it a `frequency_filter` document) and it flattened four genuinely different
facts into one cell:

    DISSOLVED     the class stops existing; no target is the FINAL answer
    DISPUTED      the record states two incompatible dispositions
    PASSTHROUGH   the decided target IS the class -- signed, and not a gap
    GAP           the target is fixed in a signed plan and nobody wrote it down

Only the last is work. Rendering it identically to the first is how a decided
model gets re-litigated and how an unrecorded one never gets found.

HOW THESE TESTS AVOID THE TRAP THEY ARE TESTING FOR
---------------------------------------------------
This repository has three tests that had to be INVERTED because they were
written from the same premise as the code they covered (CLAUDE.md: "A TEST
WRITTEN FROM THE SAME PREMISE AS THE CODE CANNOT CATCH THE CODE"). So nothing
here calls `coverage.py`'s own helpers to decide what the answer should be:

  * the sign-off transcriptions are re-checked by re-reading the plan documents
    with a parser written here, not by calling `check_decision_citations`;
  * the target expectations are PINNED as literals in this file, so deleting a
    row from the tool's table fails rather than silently changing what "correct"
    means;
  * the assertions are made against the RENDERED ARTIFACTS -- the markdown a
    human reads and the JSON the viewer reads -- not against the in-memory row
    dicts, because the defect being closed was a RENDERING that contradicted the
    data it was rendering.
"""

import json
import os
import re

import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCHEMAS = os.path.join(REPO_ROOT, "schemas")
LEDGER_MD = os.path.join(SCHEMAS, "V_eta_coverage_ledger.md")
LEDGER_JSON = os.path.join(SCHEMAS, "V_eta_coverage_ledger.json")
INDEX = os.path.join(SCHEMAS, "V_eta", "index.json")


def _ledger():
    with open(LEDGER_JSON) as fh:
        return json.load(fh)


def _rows():
    return _ledger()["rows"]


def _md():
    with open(LEDGER_MD) as fh:
        return fh.read()


def _md_row(cls):
    """The rendered markdown row for one v1 class, as (target_cell, account)."""
    for line in _md().splitlines():
        if line.startswith("| `%s` |" % cls):
            cells = line.split(" | ")
            return cells[1], cells[2]
    raise AssertionError("no rendered ledger row for `%s`" % cls)


def _built_classes():
    with open(INDEX) as fh:
        return {e["class_name"] for e in json.load(fh)["schemas"]}


# ---------------------------------------------------------------------------
# THE PINNED RECORD.
#
# Every entry is TRANSCRIBED from a `TEAM-SIGN-OFF` line, and the fragment
# beside it is re-verified against the document below. Pinning them here rather
# than importing them is the point: if someone deletes a row from
# `DECIDED_TARGETS_BY_SIGNOFF`, an imported expectation would delete itself
# alongside and the test would still pass. That is exactly how a recorded target
# vanishes silently, which is what this file exists to prevent.
# ---------------------------------------------------------------------------
PINNED_DECIDED_TARGETS = {
    "filter": (
        ["frequency_filter"],
        "V_eta_frequency_filter_model_plan.md",
        "Approved the frequency_filter model as written below"),
    "epochfiles_ingested": (
        ["ingestion_manifest"],
        "V_eta_epoch_plan.md",
        "epochfiles_ingested becomes `ingestion_manifest`"),
    "stimulus_presentation": (
        ["timed_sequence", "timed_sequence_manipulation"],
        "V_eta_stimulus_model_plan.md",
        "stimulus_presentation is DECOMPOSED around its preserved id"),
}

PINNED_DISSOLUTIONS = {
    "epochid": ("V_eta_epoch_plan.md", "epochid is DROPPED"),
    "stimulus_response": (
        "V_eta_stimulus_response_model_plan.md",
        "stimulus_response and stimulus_response_scalar_parameters DELETE"),
    "stimulus_response_scalar_parameters": (
        "V_eta_stimulus_response_model_plan.md",
        "stimulus_response and stimulus_response_scalar_parameters DELETE"),
}

# NEITHER DICTIONARY ABOVE, and pinned instead as DISPUTED. In both cases ONE
# document states two things that cannot both be acted on: a heading or section
# naming a target CLASS, and a `TEAM-SIGN-OFF` line naming a deletion or a set
# of field destinations. `ngrid` was filed each way by two commits on
# 2026-08-11, each reading one half; sweeping for the shape then found
# `binaryseries_parameters` immediately. A tool must record the disagreement,
# not settle it -- so `sampled_body` is recorded for neither.
PINNED_DISPUTED = {
    "ngrid": ("V_eta_image_model_plan.md",
              "ngrid is DISSOLVED (deleted, not migrated)",
              "phases into `sampled_body`"),
    "binaryseries_parameters": (
        "V_eta_go_forward_class_audit.md",
        "`binaryseries_parameters` folds into the data_body model and is retired",
        "`binaryseries_parameters` — folds into `sampled_body`"),
}


def _signoff_lines(plan):
    """Re-read a plan's TEAM-SIGN-OFF lines with a parser written HERE.

    Not `coverage._signoff_lines`. If the tool's parser ever went wrong -- an
    HTML-comment strip that ate real content, say -- calling it here would make
    the test agree with the bug.
    """
    path = os.path.join(SCHEMAS, plan)
    with open(path) as fh:
        text = fh.read()
    out, in_comment = [], False
    for n, line in enumerate(text.splitlines(), 1):
        s = line
        if in_comment:
            if "-->" in s:
                in_comment = False
                s = s.split("-->", 1)[1]
            else:
                continue
        while "<!--" in s:
            head, rest = s.split("<!--", 1)
            if "-->" in rest:
                s = head + rest.split("-->", 1)[1]
            else:
                s, in_comment = head, True
                break
        if s.lstrip().startswith("TEAM-SIGN-OFF"):
            out.append((n, s))
    return out


# ===========================================================================
# 1. A DISSOLUTION MUST BE EXPLICIT
# ===========================================================================

def test_no_row_asserts_a_dissolution_from_an_empty_list():
    """The old inferred wording must not come back, in any row.

    DENOMINATOR-FIRST: the count of rows read is asserted alongside, so a
    regression that emptied the table would not pass this as "no bad rows".
    """
    rows = _rows()
    assert len(rows) > 50, "ledger has %d rows -- too few to be the real one" % len(rows)
    md = _md()
    banned = "will dissolve / be deleted"
    offenders = [ln.split(" | ")[0] for ln in md.splitlines()
                 if ln.startswith("| `") and banned in ln]
    assert not offenders, (
        "%d row(s) still assert a dissolution from an empty target list: %s. "
        "A dissolution must be recorded in NO_TARGET_BY_DECISION with the "
        "sign-off that licenses it." % (len(offenders), offenders))


def test_every_no_target_row_states_why_or_renders_as_a_gap():
    """No row may name no target and say nothing about it.

    This is the anti-regression the whole change exists for: "no target" must
    stop being expressible by omission. A row with neither a target nor a
    recorded reason has to SHOW UP, not blend in.
    """
    rows = _rows()
    blank = [r for r in rows
             if not (r["targets"] or r["second_pass"] or r["decided_targets"])]
    assert blank, "no blank-target rows at all -- the ledger cannot be right"
    unexplained = []
    for r in blank:
        cell, _acct = _md_row(r["v1_class"])
        explicit = ("DISSOLVES" in cell or "DISPUTED" in cell
                    or "NO TARGET AND NO DISSOLUTION RECORDED" in cell
                    or "unmapped" in cell
                    # test/demo scaffolding and pre-V_zeta dissolutions carry
                    # their honest label in the disposition column instead.
                    or r["nonprod"] or r["disposition"].startswith("dissolved"))
        if not explicit:
            unexplained.append((r["v1_class"], cell))
    assert not unexplained, (
        "DENOMINATOR: %d rows, %d naming no target. %d of those render a cell "
        "that neither states a reason nor flags a gap: %s"
        % (len(rows), len(blank), len(unexplained), unexplained))


@pytest.mark.parametrize("cls", sorted(PINNED_DISSOLUTIONS))
def test_recorded_dissolution_quotes_a_real_signoff_line(cls):
    """The transcription is re-verified against the document, here.

    Operating rule 4: Claude records decisions, it does not make them. The only
    thing that makes that true rather than aspirational is that the quote is
    checked against a line the TEAM wrote.
    """
    plan, fragment = PINNED_DISSOLUTIONS[cls]
    lines = _signoff_lines(plan)
    assert lines, "%s carries no TEAM-SIGN-OFF line at all" % plan
    hits = [n for n, ln in lines if fragment in ln]
    assert hits, (
        "%s: no TEAM-SIGN-OFF line in %s contains %r (checked %d sign-off "
        "line(s))" % (cls, plan, fragment, len(lines)))
    row = next(r for r in _rows() if r["v1_class"] == cls)
    assert row["no_target_reason"] == "dissolved", (
        "%s is signed as a dissolution at %s:%d but the ledger records "
        "no_target_reason=%r" % (cls, plan, hits[0], row["no_target_reason"]))


@pytest.mark.parametrize("cls", sorted(PINNED_DISPUTED))
def test_a_contested_row_stays_contested_and_names_no_target(cls):
    """Where the record contradicts itself, it stays contradictory.

    Recording `sampled_body` would promote a reading over a signature;
    recording a clean dissolution would bury a disagreement that has already
    flipped `ngrid` twice in one day. Neither, and BOTH halves must still be
    present in the document -- if one disappears the dispute is over and this
    test should be revisited rather than relaxed.
    """
    plan, signoff_frag, other_frag = PINNED_DISPUTED[cls]
    row = next(r for r in _rows() if r["v1_class"] == cls)
    assert row["no_target_reason"] == "disputed", (
        "%s: no_target_reason=%r" % (cls, row["no_target_reason"]))
    assert not row["decided_targets"], (
        "%s names %s as a decided target while its record is contested. A tool "
        "must not pick." % (cls, row["decided_targets"]))
    cell, _ = _md_row(cls)
    assert "DISPUTED" in cell, (cls, cell)

    with open(os.path.join(SCHEMAS, plan)) as fh:
        text = fh.read()
    hits = [n for n, ln in _signoff_lines(plan) if signoff_frag in ln]
    assert hits, "%s: no TEAM-SIGN-OFF line in %s contains %r" % (
        cls, plan, signoff_frag)
    assert other_frag in text, (
        "%s: the OTHER half of the dispute (%r) is no longer in %s. If the "
        "document now says only one thing, the dispute is resolved and this "
        "row needs re-recording -- do not simply delete the assertion."
        % (cls, other_frag, plan))


# ===========================================================================
# 2. A RECORDED TARGET MUST NOT SILENTLY VANISH
# ===========================================================================

@pytest.mark.parametrize("cls", sorted(PINNED_DECIDED_TARGETS))
def test_recorded_decided_target_survives_in_both_artifacts(cls):
    """Pinned literal -> ledger JSON -> rendered markdown, all three.

    A target that reaches the JSON but never the table is invisible to the
    person the table is for; that is not hypothetical here, since until
    2026-08-11 only rows with NO emitted target printed their decided ones, so
    `epochfiles_ingested -> ingestion_manifest` and four `method_parameters`
    folds sat in the JSON unrendered.
    """
    want, plan, fragment = PINNED_DECIDED_TARGETS[cls]
    hits = [n for n, ln in _signoff_lines(plan) if fragment in ln]
    assert hits, "%s: %s has no TEAM-SIGN-OFF line containing %r" % (
        cls, plan, fragment)

    row = next(r for r in _rows() if r["v1_class"] == cls)
    assert sorted(row["decided_targets"]) == sorted(want), (
        "%s: ledger records decided_targets=%s, signed record says %s "
        "(%s:%d)" % (cls, row["decided_targets"], want, plan, hits[0]))

    cell, _acct = _md_row(cls)
    for t in want:
        assert "`%s`" % t in cell, (
            "%s: `%s` is a recorded decided target but does not appear in the "
            "rendered target cell %r" % (cls, t, cell))
    assert "will become" in cell, (
        "%s: a decided target must be rendered in the FUTURE voice, so it "
        "cannot be misread as something a migrator emits today: %r" % (cls, cell))


def test_every_recorded_decided_target_names_a_class_that_exists():
    """A target nobody can find is a typo, not a plan."""
    built = _built_classes()
    rows = _rows()
    bad = [(r["v1_class"], t) for r in rows
           for t in r["decided_targets"] if t not in built]
    assert not bad, (
        "DENOMINATOR: %d rows, %d built classes. Decided targets naming no "
        "built class: %s" % (len(rows), len(built), bad))


def test_a_decided_target_is_recorded_in_exactly_one_place():
    """Two records of one fact agree by coincidence until they do not.

    The curated `V_eta_migration_targets.json` and the sign-off transcriptions
    in `coverage.py` must never both name a class. This repository already has
    one live instance of the same shape open (#32, binding strength stated on
    both the field and the registry, agreeing today "by coincidence rather than
    by construction"); it is not worth a second.
    """
    with open(os.path.join(SCHEMAS, "V_eta_migration_targets.json")) as fh:
        curated = json.load(fh)["classes"]
    rows = _rows()
    both = []
    for r in rows:
        if r.get("decided_targets_source") != "signoff_transcription":
            continue
        entry = curated.get(r["v1_class"]) or {}
        if entry.get("decided_targets"):
            both.append(r["v1_class"])
    assert not both, (
        "DENOMINATOR: %d rows, %d transcribed from a sign-off. Recorded twice: "
        "%s" % (len(rows), len(_ledger()["summary"]
                                ["decided_targets_from_signoff_transcription"]),
                both))


def test_the_gap_list_is_enumerated_not_merely_counted():
    """A count with no names is not actionable, and cannot be checked."""
    s = _ledger()["summary"]["no_target"]
    gaps = s["target_gaps"]
    assert s["by_reason"]["unrecorded"] == len(gaps), (
        "the gap COUNT (%d) and the gap LIST (%d) disagree"
        % (s["by_reason"]["unrecorded"], len(gaps)))
    md = _md()
    for g in gaps:
        assert "`%s`" % g in md, "gap `%s` is counted but never named" % g


# ===========================================================================
# 3. BUILD STATE IS TWO HALVES, NEVER ONE FLAG
# ===========================================================================

def test_build_state_reports_schema_and_migrator_separately():
    """One flag reads as neither half.

    The authored `flags` prose says "DECIDED AND SIGNED, BUILD NOT DONE" on
    eight rows. For `app` the schema half is DONE -- `software` is built and
    shipping, plus an `execution_environment` block on `subject_interaction` --
    and only the migrator is outstanding. A reader acting on the
    undifferentiated sentence re-authors schema that already exists.
    """
    rows = [r for r in _rows() if r["decided_targets"]]
    assert rows, "no row names a decided target -- the ledger cannot be right"
    for r in rows:
        bs = r.get("build_state") or {}
        for key in ("schema_targets_named", "schema_targets_built",
                    "schema_targets_missing", "migrator_emits_decided_targets"):
            assert key in bs, "%s: build_state has no %r" % (r["v1_class"], key)
        assert (len(bs["schema_targets_built"]) + len(bs["schema_targets_missing"])
                == bs["schema_targets_named"]), (
            "%s: build_state does not partition its own targets" % r["v1_class"])
        _cell, acct = _md_row(r["v1_class"])
        assert "SCHEMA:" in acct and "MIGRATOR:" in acct, (
            "%s: the rendered account states build state without splitting it "
            "into a schema half and a migrator half: %r" % (r["v1_class"], acct))


def test_app_schema_half_is_reported_as_built():
    """The specific row the conflation was found on.

    `software` exists in the built set. The row's authored caveat says "BUILD
    NOT DONE"; the DERIVED clause beside it must say the schema half is
    present, so the two halves cannot be read as one verdict.
    """
    row = next(r for r in _rows() if r["v1_class"] == "app")
    assert row["decided_targets"] == ["software"], row["decided_targets"]
    assert "software" in _built_classes(), (
        "`software` is not in the built set -- re-check this test's premise "
        "before relaxing it")
    bs = row["build_state"]
    assert bs["schema_targets_built"] == ["software"], bs
    assert bs["schema_targets_missing"] == [], bs
    assert bs["migrator_emits_decided_targets"] is False, bs
    _cell, acct = _md_row("app")
    assert "BUILD NOT DONE" in acct, (
        "the authored caveat is expected to still be present -- this test is "
        "about the derived clause CORRECTING it, not about deleting it")
    assert "SCHEMA: 1 of 1 decided target class(es) present in the built set" in acct, acct
    assert "MIGRATOR: does NOT emit them yet" in acct, acct


def test_a_corrupted_signoff_citation_stops_the_ledger():
    """The transcriptions are re-read, not remembered.

    A quote that has gone stale -- a plan reworded, a document renamed -- must
    STOP the build, not be carried forward. Six plan documents in this
    repository spent two days denying sign-offs they carried; the difference
    between a citation and a recollection is whether anything re-opens the file.
    """
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "cov_under_test", os.path.join(REPO_ROOT, "tools", "coverage.py"))
    cov = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(cov)

    lines, fails = cov.check_decision_citations()
    assert not fails, fails
    assert lines and lines[0].startswith("DENOMINATOR:"), (
        "the citation check must state how many transcriptions it read, first "
        "and unconditionally (operating rule 5): %r" % (lines[:1],))
    n_checked = len(cov.NO_TARGET_BY_DECISION) + len(cov.DECIDED_TARGETS_BY_SIGNOFF)
    assert "DENOMINATOR: %d " % n_checked in lines[0], (lines[0], n_checked)

    # Now corrupt one in a SUBPROCESS copy of the module's tables and confirm
    # the check reports it rather than shrugging.
    cov.NO_TARGET_BY_DECISION["epochid"] = (
        cov.NO_TARGET_DISSOLVED, "V_eta_epoch_plan.md",
        "epochid is KEPT AND CELEBRATED", "fabricated")
    _lines, fails = cov.check_decision_citations()
    assert fails and any("epochid" in f for f in fails), (
        "a fabricated sign-off quote passed the citation check: %s" % (fails,))


def test_the_board_does_not_assert_what_it_never_read():
    """The status board's unchecked-family prose must be measured.

    It used to print "No member of these families carries a `decided_targets`
    entry in the coverage ledger" about eleven families. Measured 2026-08-11
    that was FALSE for five of them -- all four members of `spike processing
    parameters` carry `decided_targets: [method_parameters]`, and `stimulus
    response` carries two more. The lookup only ever touched
    `open_class_state`, which does not cover a `retire` v1 source row, so it
    was a claim about the ledger produced without reading the ledger.
    """
    status = os.path.join(SCHEMAS, "V_eta_STATUS.md")
    with open(status) as fh:
        text = fh.read()
    banned = ("No member of these families carries a `decided_targets` entry "
              "in the coverage ledger")
    assert banned not in text, (
        "the board still asserts that no member of the unchecked families "
        "carries a decided target -- a statement it does not measure")

    # And the families it DOES report as unchecked must really be unchecked:
    # not one of their members may carry a non-self decided target.
    rows = {r["v1_class"]: r for r in _rows()}
    m = re.search(r"\*\*The other (\d+) are unchecked, NOT clean\.\*\*(.*?)\n\n"
                  r"Only the", text, re.S)
    assert m, "could not find the unchecked-families block in V_eta_STATUS.md"
    named = re.findall(r"^- \*\*(.+?)\*\* \(\d+ class", m.group(2), re.M)
    assert len(named) == int(m.group(1)), (
        "the board says %s families are unchecked and then lists %d"
        % (m.group(1), len(named)))
    listed = re.findall(r"`([A-Za-z_][\w]*)`", m.group(2))
    wrong = [c for c in listed
             if c in rows
             and [t for t in rows[c]["decided_targets"] if t != c]]
    assert not wrong, (
        "DENOMINATOR: %d class(es) named in the unchecked block, %d present in "
        "the ledger. These carry a decided target and must not be reported as "
        "contributing nothing: %s"
        % (len(listed), sum(1 for c in listed if c in rows), wrong))


def test_the_family_prose_is_swept_against_the_signatures():
    """The `ngrid` split must be looked for, not stumbled on.

    Two independent readers got `ngrid` wrong on the same day, each from the
    same document, because the FAMILIES one-liner (Claude-authored prose in a
    tool) named a target class the signature does not. Sweeping for that shape
    found a second instance in the first pass. A one-off correction leaves the
    third one to be discovered the same way.
    """
    status = os.path.join(SCHEMAS, "V_eta_STATUS.md")
    with open(status) as fh:
        text = fh.read()
    heading = "## Class names the family table asserts that its sign-off does not say"
    assert heading in text, "the family-prose sweep is not rendered in the board at all"

    # SCOPE THE ASSERTIONS TO THE SWEEP'S OWN SECTION. The first draft of this
    # test searched the WHOLE of V_eta_STATUS.md for "image / ngrid" and
    # "sampled_body" -- both of which appear in the family table two sections
    # up -- so a mutation that narrowed the sweep until it reported NOTHING
    # still passed. Caught by mutating it (M13); the test agreed with the
    # broken code because it was reading a different part of the file.
    section = text.split(heading, 1)[1].split("\n## ", 1)[0]

    m = re.search(r"DENOMINATOR: (\d+) signed families checked;.*?"
                  r"(\d+) family/name pair\(s\) are\s+UNSIGNED", section, re.S)
    assert m, "the sweep does not state its denominator"
    assert int(m.group(1)) >= 15, (
        "the sweep claims to have checked only %s families -- too few to be the "
        "real set" % m.group(1))
    assert int(m.group(2)) > 0, (
        "the sweep reports 0 unsigned family/name pairs. Two are known and "
        "documented (`ngrid` and `binaryseries_parameters`, both naming "
        "`sampled_body`), so a zero here means the sweep was narrowed, not that "
        "the record was fixed.")
    # The rows it exists for must be in ITS OWN table.
    assert "| **image / ngrid** |" in section, (
        "the sweep no longer reports the family it was built from")
    assert "`sampled_body`" in section, (
        "`sampled_body` -- the unsigned class name in BOTH contested rows -- is "
        "not reported by the sweep")


def test_a_row_whose_migrator_emits_its_decided_target_says_so():
    """The other side of the same split, so it cannot be a constant.

    A clause that always prints "MIGRATOR: does NOT emit them yet" measures
    nothing. At least one row must reach the other branch, or this half of the
    split is untested rather than passing.
    """
    rows = [r for r in _rows() if r["decided_targets"]]
    emitting = [r["v1_class"] for r in rows
                if r["build_state"]["migrator_emits_decided_targets"]]
    assert emitting, (
        "DENOMINATOR: %d rows naming a decided target; NONE reach the "
        "'migrator emits them' branch, so that branch is unexercised and this "
        "split is a constant in disguise." % len(rows))
    for cls in emitting:
        _cell, acct = _md_row(cls)
        assert "MIGRATOR: emits them today" in acct, (cls, acct)
