// Copies every versioned schema set (schemas/V_*) that has an index.json into
// web/public/schemas/<set>, and writes a versions.json manifest the app uses
// to populate the set-version selector. Runs automatically before `npm run
// dev` and `npm run build`.
import { cp, rm, mkdir, readdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..");
const schemasDir = resolve(repoRoot, "schemas");
const publicDir = resolve(here, "..", "public");
const publicSchemas = resolve(publicDir, "schemas");

// Set versions are named after Greek letters; order them so the newest set is
// the default. Unknown names sort after the known ones, then alphabetically.
const GREEK = [
  "alpha", "beta", "gamma", "delta", "epsilon", "zeta", "eta", "theta",
  "iota", "kappa", "lambda", "mu", "nu", "xi", "omicron", "pi",
];
function rank(name) {
  const m = /^V_([a-z]+)$/.exec(name);
  const i = m ? GREEK.indexOf(m[1]) : -1;
  return i === -1 ? 999 : i;
}

const entries = await readdir(schemasDir, { withFileTypes: true });
const versions = entries
  .filter(
    (d) =>
      d.isDirectory() &&
      /^V_/.test(d.name) &&
      existsSync(resolve(schemasDir, d.name, "index.json")),
  )
  .map((d) => d.name)
  .sort((a, b) => rank(a) - rank(b) || a.localeCompare(b));

if (versions.length === 0) {
  console.error(`sync-schemas: no V_* schema sets with index.json under ${schemasDir}`);
  process.exit(1);
}

await rm(publicSchemas, { recursive: true, force: true });
await mkdir(publicSchemas, { recursive: true });
for (const v of versions) {
  await cp(resolve(schemasDir, v), resolve(publicSchemas, v), { recursive: true });
  console.log(`sync-schemas: copied ${v}`);
}

const defaultVersion = versions[versions.length - 1];
await writeFile(
  resolve(publicSchemas, "versions.json"),
  JSON.stringify({ versions, default: defaultVersion }, null, 2) + "\n",
);
console.log(
  `sync-schemas: ${versions.length} set(s) [${versions.join(", ")}], default ${defaultVersion}`,
);

// The V_eta migration coverage ledger (generated by tools/coverage.py) powers the
// Coverage panel. Copy the machine-readable JSON to public/coverage.json so the app
// can fetch it. Non-fatal if absent (older checkout / coverage.py not yet run).
const ledgerSrc = resolve(schemasDir, "V_eta_coverage_ledger.json");
if (existsSync(ledgerSrc)) {
  await cp(ledgerSrc, resolve(publicDir, "coverage.json"));
  console.log("sync-schemas: copied V_eta_coverage_ledger.json -> coverage.json");
} else {
  console.warn("sync-schemas: no V_eta_coverage_ledger.json (run tools/coverage.py)");
}

// The decision families (generated by tools/status_board.py). The ledger says
// what a class's disposition IS; this says whether the model behind it has been
// decided and signed off. Without it the viewer showed a settled, signed family
// awaiting build as plain `in_progress` -- indistinguishable from undecided.
const decisionsSrc = resolve(schemasDir, "V_eta_decisions.json");
if (existsSync(decisionsSrc)) {
  await cp(decisionsSrc, resolve(publicDir, "decisions.json"));
  console.log("sync-schemas: copied V_eta_decisions.json -> decisions.json");
} else {
  console.warn("sync-schemas: no V_eta_decisions.json (run tools/status_board.py)");
}
