#!/usr/bin/env python3
"""Every file the web viewer SERVES must equal the artifact it is a copy of.

WHY THIS EXISTS
---------------
`web/public/` holds no original content. Every file under it is produced by
something else: `web/scripts/sync-schemas.mjs` copies the whole `V_*` schema
sets, the generated coverage ledger and the generated decision families into
it, writes one manifest in place, and a tool under `tools/` may write a
served file directly. Four of those sources are regenerated by
`tools/gates.py` and cannot drift. THE COPIES WERE GATED BY NOTHING, and on
2026-08-12 they had drifted:

    served    web/public/coverage.json               md5 0e98cc86
    generated schemas/V_eta_coverage_ledger.json     md5 3ae3465d
    102 rows both sides, 97 identical, 5 DIFFERENT, 0 missing either way

and the direction was the one this repository keeps paying for. The served copy
graded `binaryseries_parameters` as `no_target_reason: disputed` -- "DISPUTED,
the record states two incompatible dispositions" -- while the generated ledger
had it RESOLVED, with two decided targets and a sign-off citation. A settled
question rendered as open, in the panel a reader consults to find out which
questions are still open.

WHAT IT DOES NOT CLAIM
----------------------
`web/public/` is GITIGNORED and has never been tracked (`git log --all
--diff-filter=A -- 'web/public/*'` is empty), and both viewer workflows run
`npm run build`, whose `prebuild` hook runs the sync. So the DEPLOYED site
cannot be stale with respect to its commit. The staleness this catches is the
WORKING TREE's: a checkout where `schemas/` has been regenerated since the last
sync, which is every checkout where anyone has run `tools/gates.py`. That is
where the measurement above came from, and it is where a reader reads.

THE CONTRACT IS DERIVED, NOT RESTATED. Which served file is a copy of what is
read out of `sync-schemas.mjs` itself, because a second copy of that mapping
kept beside it is exactly the drift being gated. A served file the sync script
does not explain is not waved through either: its basename is looked for in
`tools/*.py`, so a file written directly into `public/` by a generator is
PAIRED WITH THAT GENERATOR and its freshness delegated to the generator's own
`--check`. Only a file nothing produces is UNPAIRABLE.

What this file does restate is the SELECTION rule for whole schema sets (a
`V_*` directory with an `index.json`), and that restatement is checked against
the script's own text -- if the script stops saying it, this tool stops rather
than grading against a rule the script no longer follows.

RULE 5. The denominator prints first and unconditionally: served files
inspected, how many paired with a generator, how many the contract explains as
generated-in-place, and how many are UNPAIRABLE. An unpairable served file is
NAMED and FAILS -- it is the shape of "found nothing" that is really "looked in
the wrong place". Zero served files inspected is likewise a FAILURE, never a
clean zero.

BOTH DIRECTIONS, AND THE SECOND ONE EARNED ITS KEEP IMMEDIATELY. A source the
contract serves with no served copy is a finding, not an absence -- because a
sync that dies partway leaves every file it DID copy perfectly correct. Caught
on 2026-08-12, a sync interrupted inside its last set:

    DENOMINATOR: 769 served file(s) inspected, 904 the contract says exist
    V_delta   135/135    V_epsilon 249/249    V_zeta 240/240
    V_eta     141/278   <-- interrupted here
    STALE 32   ORPHANED 13   UNSERVED 150   UNPAIRABLE 0

A checker that only compared the files present would have reported 32 stale and
missed 150 classes the viewer had simply stopped serving.
"""

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SYNC_SCRIPT = os.path.join("web", "scripts", "sync-schemas.mjs")
PUBLIC = os.path.join("web", "public")
SCHEMAS = "schemas"
TOOLS = "tools"

# Artifacts that are viewer INPUTS and are generated by the chain in
# tools/gates.py. If one of these exists in the tree and the sync contract does
# not serve it, the contract has a hole -- the viewer would go on rendering
# whatever copy it last had. Checked only when the file is present, so this is
# a statement about THIS repository, not a hard-coded shadow of the contract.
#
#   schemas/V_eta_coverage_ledger.json  -> the Coverage panel (tools/coverage.py)
#   schemas/V_eta_decisions.json        -> the decision families (status_board.py)
GATED_INPUTS = (
    "V_eta_coverage_ledger.json",
    "V_eta_decisions.json",
)

# The schema set the viewer defaults to. Named for the same reason: if the
# contract ever stops serving it, no panel has anything to render.
GATED_SET = "V_eta"


class ContractError(Exception):
    """The sync script could not be read as a contract. Never a soft skip: a
    contract that cannot be derived is not an empty contract."""


def same_bytes(a, b):
    """THE COMPARISON. One function, on purpose.

    Every byte-level staleness verdict in this file goes through here, so a
    mutation that makes it return True unconditionally turns the whole tool
    into a clean report -- which is what `tests/test_web_assets_fresh.py` stubs
    it to, to prove the stale finding is really driven by the comparison and
    not by some incidental property of the fixture."""
    return _digest(a) == _digest(b)


def _digest(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


# --------------------------------------------------------------------------
# the contract, read out of the sync script
# --------------------------------------------------------------------------

_FILE_SRC_RE = re.compile(r'const\s+(\w+)\s*=\s*resolve\(\s*schemasDir\s*,\s*"([^"]+)"\s*\)')
_FILE_DST_RE = re.compile(r'cp\(\s*(\w+)\s*,\s*resolve\(\s*publicDir\s*,\s*"([^"]+)"\s*\)')
_INPLACE_RE = re.compile(r'writeFile\(\s*resolve\(\s*(publicSchemas|publicDir)\s*,\s*"([^"]+)"\s*\)')
_SET_CP_RE = re.compile(r'cp\(\s*resolve\(\s*schemasDir\s*,\s*(\w+)\s*\)\s*,\s*resolve\(\s*publicSchemas\s*,\s*\1\s*\)')


def read_contract(root):
    """Return (file_copies, inplace, set_root) from the sync script's own text.

    file_copies -- {served path relative to web/public: source name under schemas/}
    inplace     -- {served path relative to web/public: 'publicSchemas'|'publicDir'}
    set_root    -- the served subdirectory whole schema sets are copied into,
                   or None if the script does not copy sets at all.
    """
    p = os.path.join(root, SYNC_SCRIPT)
    if not os.path.exists(p):
        raise ContractError(
            f"{SYNC_SCRIPT} does not exist -- there is no contract to derive, and "
            "an absent contract is not an empty one")
    with open(p, encoding="utf-8", errors="replace") as fh:
        src = fh.read()

    srcs = dict(_FILE_SRC_RE.findall(src))
    copies = {}
    for var, served in _FILE_DST_RE.findall(src):
        if var in srcs:
            copies[served] = srcs[var]

    inplace = {}
    for where, name in _INPLACE_RE.findall(src):
        served = os.path.join("schemas", name) if where == "publicSchemas" else name
        inplace[served] = where

    set_root = None
    if _SET_CP_RE.search(src):
        # The SELECTION rule is restated here and immediately checked against
        # the script, because grading whole directory trees needs it and a rule
        # the script no longer follows must stop this tool rather than let it
        # quietly grade the wrong set of directories.
        missing = [lit for lit in ('/^V_/', "index.json", "publicSchemas")
                   if lit not in src]
        if missing:
            raise ContractError(
                "the schema-set copy no longer states its selection rule "
                f"({', '.join(missing)} absent from {SYNC_SCRIPT}); this tool "
                "restates that rule and refuses to grade against a stale one")
        set_root = "schemas"

    if not copies and set_root is None and not inplace:
        raise ContractError(
            f"nothing in {SYNC_SCRIPT} parsed as a copy -- the derivation is "
            "stale, not the tree")
    return copies, inplace, set_root


def schema_sets(root):
    """The `V_*` directories the sync script would copy: the rule it states."""
    d = os.path.join(root, SCHEMAS)
    if not os.path.isdir(d):
        return []
    return sorted(name for name in os.listdir(d)
                  if name.startswith("V_")
                  and os.path.isfile(os.path.join(d, name, "index.json")))


def source_of(served_rel, copies, set_root, sets):
    """The repo-relative path a served file is a copy OF, by PATH RULE.

    By rule and not by enumerating what exists, so that a served file whose
    source has been DELETED still resolves to a name -- that is an ORPHAN, and
    it must be distinguishable from a served file the contract never explained
    at all."""
    parts = served_rel.split(os.sep)
    if served_rel in copies:
        return os.path.join(SCHEMAS, copies[served_rel])
    if set_root is not None and len(parts) > 2 and parts[0] == set_root \
            and parts[1] in sets:
        return os.path.join(SCHEMAS, *parts[1:])
    return None


# --------------------------------------------------------------------------
# generators that write into public/ directly
# --------------------------------------------------------------------------

# Writing a file is what makes a tool its GENERATOR. A tool that merely reads a
# served file, or names one in prose, is not.
_WRITE_IDIOMS = ("write_text(", ".write(", "json.dump", 'open(', "writelines(")


def _mentions_in_code(body, needle):
    """Does `needle` appear on a line that is not a comment?

    NOT A COSMETIC REFINEMENT -- it was a live false positive. `tools/gates.py`
    names `web/public/class_walkthrough.json` in a COMMENT explaining why the
    step's path precondition is the subtree rather than its parent, and a bare
    substring search therefore reported two generators for one file and failed
    the run as AMBIGUOUS. A mention is not a write; the same distinction
    `check_pipeline_parity` draws when it excludes comment-only lines."""
    for line in body.splitlines():
        i = line.find(needle)
        if i < 0:
            continue
        hash_at = line.find("#")
        if hash_at == -1 or hash_at > i:
            return True
    return False


def find_generator(root, served_rel):
    """Which tool under tools/ produces this served file, if any.

    Discovery is by BASENAME across `tools/*.py`, not a list kept here: a list
    would be one more copy of a mapping that already exists in the tool that
    does the writing. A tool qualifies only if it names the file OUTSIDE a
    comment and contains a write idiom -- naming a file and writing it are
    different things, and a reader is not a generator.

    Returns (list of relative tool paths, whether the single match offers
    --check). More than one match is returned as a LIST rather than resolved:
    an ambiguous answer is reported, never guessed."""
    base = os.path.basename(served_rel)
    tdir = os.path.join(root, TOOLS)
    hits = []
    if not os.path.isdir(tdir):
        return [], False
    me = os.path.basename(__file__)
    # THE DRIVER IS NEVER A GENERATOR, and this exclusion is structural rather
    # than a special case. `tools/gates.py` names EVERY artifact in the chain,
    # in each step's `writes=[...]`, which is ordinary code and not a comment --
    # so the comment-vs-code rule above cannot separate it, and it also contains
    # write idioms of its own. It declares what other tools write; it writes
    # none of them.
    #
    # It was the comment case first (see `_mentions_in_code`) and became the
    # code case on 2026-08-12, when `gen_class_walkthrough` and `tenet_map` were
    # wired into the chain and their assets appeared in `writes=`. Both served
    # files immediately went AMBIGUOUS between the driver and their real
    # generator. Excluding the driver by name is narrower than relaxing the
    # ambiguity rule, which is the check that stops a served file being
    # attributed to a tool that merely mentions it.
    driver = "gates.py"
    for name in sorted(os.listdir(tdir)):
        if not name.endswith(".py") or name == me or name == driver:
            continue
        p = os.path.join(tdir, name)
        try:
            with open(p, encoding="utf-8", errors="replace") as fh:
                body = fh.read()
        except OSError:
            continue
        if _mentions_in_code(body, base) and "public" in body \
                and any(idiom in body for idiom in _WRITE_IDIOMS):
            hits.append((os.path.join(TOOLS, name), "--check" in body))
    return [h[0] for h in hits], (hits[0][1] if len(hits) == 1 else False)


def _walk(root):
    out = []
    for base, dirs, files in os.walk(root):
        dirs.sort()
        for f in sorted(files):
            out.append(os.path.relpath(os.path.join(base, f), root))
    return sorted(out)


def check_versions_manifest(root, served_rel, sets):
    """The one served file that is WRITTEN, not copied.

    Only what can be checked without restating the script's ordering table is
    checked: the manifest must name exactly the sets the selection rule finds,
    and its default must be the last of them. The ORDER is the script's
    Greek-letter ranking and is deliberately NOT recomputed here -- saying so is
    the point, because a check that silently covers less than it appears to is
    the defect this repository keeps finding."""
    p = os.path.join(root, PUBLIC, served_rel)
    try:
        with open(p, encoding="utf-8") as fh:
            man = json.load(fh)
    except (OSError, ValueError) as exc:
        return [f"{served_rel}: unreadable as JSON ({exc})"]
    problems = []
    got = man.get("versions")
    if not isinstance(got, list) or sorted(got) != sorted(sets):
        problems.append(
            f"{served_rel}: names {got!r}; the selection rule finds {sets!r}")
    elif man.get("default") != got[-1]:
        problems.append(
            f"{served_rel}: default is {man.get('default')!r}, not the last "
            f"entry {got[-1]!r}")
    return problems


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Compare every file the viewer serves against the artifact "
                    "it is a copy of.")
    ap.add_argument("--root", default=REPO,
                    help="repository root to inspect (default: this checkout)")
    ap.add_argument("--no-delegate", action="store_true",
                    help="do not run a discovered generator's own --check; "
                         "report the delegation instead of performing it")
    a = ap.parse_args(argv)
    root = os.path.abspath(a.root)

    print("WEB ASSET FRESHNESS -- web/public/ holds no originals; every file "
          "under it is produced by something else")
    try:
        copies, inplace, set_root = read_contract(root)
    except ContractError as exc:
        print(f"DENOMINATOR: 0 served file(s) inspected under {PUBLIC}")
        print(f"CONTRACT UNREADABLE: {exc}")
        return 1

    sets = schema_sets(root)
    pub = os.path.join(root, PUBLIC)
    served = _walk(pub) if os.path.isdir(pub) else []

    # ---- pairing, by rule -------------------------------------------------
    pair = {}            # served -> source (repo-relative), by contract
    generated = {}       # served -> [tool] written directly by a generator
    unpairable = []
    for s in served:
        if s in inplace:
            continue
        src = source_of(s, copies, set_root, sets)
        if src is not None:
            pair[s] = src
            continue
        tools_, _has_check = find_generator(root, s)
        if tools_:
            generated[s] = tools_
        else:
            unpairable.append(s)

    # every source the contract says is served, for the other direction
    expected = {}
    for servedname, srcname in copies.items():
        expected[servedname] = os.path.join(SCHEMAS, srcname)
    if set_root is not None:
        for s in sets:
            base = os.path.join(root, SCHEMAS, s)
            for rel in _walk(base):
                expected[os.path.join(set_root, s, rel)] = os.path.join(SCHEMAS, s, rel)

    # ---- RULE 5: first, unconditionally, before any verdict ---------------
    print(f"DENOMINATOR: {len(served)} served file(s) inspected under {PUBLIC}")
    print(f"             {len(pair)} paired with a generator source (copied by "
          "the sync contract)")
    print(f"             {len(generated)} paired with a generator TOOL that "
          "writes into public/ directly")
    print(f"             {len([s for s in served if s in inplace])} written in "
          "place by the sync script (checked structurally, not byte for byte)")
    print(f"             {len(unpairable)} UNPAIRABLE -- produced by nothing "
          "this tool can find")
    print(f"             {len(expected)} path(s) the sync contract says are served")
    print()
    print(f"CONTRACT, derived from {SYNC_SCRIPT}:")
    print(f"  schema sets copied whole : {len(sets) if set_root else 0}"
          f"  {sets if set_root else []}")
    print(f"  single files copied      : {len(copies)}")
    for servedname, src in sorted(copies.items()):
        print(f"      schemas/{src}  ->  {servedname}")
    print(f"  written in place         : {len(inplace)}"
          f"  {sorted(inplace) if inplace else ''}")
    print()

    problems = []

    # 1. a served copy whose source no longer exists
    orphaned = [s for s in sorted(pair)
                if not os.path.exists(os.path.join(root, pair[s]))]
    # 2. a served copy whose bytes differ from the source
    stale = [s for s in sorted(pair)
             if s not in orphaned
             and not same_bytes(os.path.join(pub, s), os.path.join(root, pair[s]))]
    # 3. a source the contract serves with no served copy at all
    have = set(served)
    unserved = [s for s in sorted(expected)
                if s not in have and os.path.exists(os.path.join(root, expected[s]))]

    print(f"STALE -- served bytes differ from the source: {len(stale)}")
    for s in stale:
        print(f"    {PUBLIC}/{s}\n        <- {pair[s]}")
    print(f"ORPHANED -- served, but the source no longer exists: {len(orphaned)}")
    for s in orphaned:
        print(f"    {PUBLIC}/{s}   (source {pair[s]} is gone)")
    print(f"UNSERVED -- the contract serves it, no served copy exists: {len(unserved)}")
    for s in unserved:
        print(f"    {expected[s]}   (would be served at {PUBLIC}/{s})")
    print(f"UNPAIRABLE -- served, produced by nothing this tool can find: {len(unpairable)}")
    for s in unpairable:
        print(f"    {PUBLIC}/{s}")
    problems += [f"STALE {s}" for s in stale]
    problems += [f"ORPHANED {s}" for s in orphaned]
    problems += [f"UNSERVED {expected[s]}" for s in unserved]
    problems += [f"UNPAIRABLE {s}" for s in unpairable]

    # 4. served files a TOOL writes directly: freshness is that tool's own
    #    --check, composed rather than reimplemented. A generator that offers
    #    no --check leaves its served file UNVERIFIABLE, and that is a finding,
    #    not a pass.
    print(f"WRITTEN BY A TOOL -- freshness delegated to the generator: {len(generated)}")
    for s in sorted(generated):
        tools_ = generated[s]
        if len(tools_) != 1:
            print(f"    {PUBLIC}/{s}   AMBIGUOUS: {tools_}")
            problems.append(f"AMBIGUOUS GENERATOR {s}")
            continue
        tool = tools_[0]
        with open(os.path.join(root, tool), encoding="utf-8", errors="replace") as fh:
            offers = "--check" in fh.read()
        if not offers:
            print(f"    {PUBLIC}/{s}   <- {tool}   NO --check: UNVERIFIABLE")
            problems.append(f"UNVERIFIABLE {s}")
            continue
        if a.no_delegate:
            print(f"    {PUBLIC}/{s}   <- {tool} --check   (not run: --no-delegate)")
            continue
        p = subprocess.run([sys.executable, os.path.join(root, tool), "--check"],
                           cwd=root, capture_output=True, text=True, check=False)
        verdict = "OK" if p.returncode == 0 else f"FAIL exit={p.returncode}"
        print(f"    {PUBLIC}/{s}   <- {tool} --check   {verdict}")
        if p.returncode != 0:
            for ln in (p.stdout + p.stderr).strip().splitlines()[-6:]:
                print("        | " + ln)
            problems.append(f"GENERATOR --check FAILED {tool} ({s})")

    # 5. the written-in-place manifest
    manifest = []
    for s in sorted(inplace):
        if s not in have:
            manifest.append(f"{s}: the script writes it, nothing serves it")
        elif os.path.basename(s) == "versions.json":
            manifest += check_versions_manifest(root, s, sets)
    print(f"WRITTEN-IN-PLACE problems: {len(manifest)}")
    for m in manifest:
        print(f"    {m}")
    problems += manifest

    # 6. a generated viewer input the contract does not serve at all
    hole = []
    for name in GATED_INPUTS:
        if os.path.exists(os.path.join(root, SCHEMAS, name)) and \
                name not in set(copies.values()):
            hole.append(f"schemas/{name} exists and the contract serves no copy of it")
    if GATED_SET in sets and set_root is None:
        hole.append(f"schemas/{GATED_SET} exists and the contract serves no copy of it")
    print(f"CONTRACT HOLES -- a generated viewer input nothing serves: {len(hole)}")
    for h in hole:
        print(f"    {h}")
    problems += hole

    print()
    if not served:
        print("NOT SYNCED: 0 served file(s). Nothing is served from this "
              "checkout, so nothing here can be compared -- that is a "
              "denominator of zero, NOT a clean result. Run:")
        print(f"    node {SYNC_SCRIPT}")
        return 1
    if problems:
        print(f"FAIL: {len(problems)} problem(s). The served copies are not the "
              "artifacts they claim to be copies of. Run:")
        print(f"    node {SYNC_SCRIPT}")
        return 1
    print(f"OK: all {len(pair)} copied served file(s) equal their source, "
          f"{len(generated)} tool-written, 0 unpairable.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
