#!/usr/bin/env python3
"""Regenerate schemas/V_eta_final_class_set.md from the BUILT schema's index.json.

The final class set is derived, never hand-authored -- run this after
build_v_eta.py so the doc never drifts from the schema. Categories (fixed order):
  (1) spine & genus  (2) entities  (3) composites (data_type)
  (4) data-type leaf tier  (5) time_reference family  (6) data_body (exactly 2)
  (7) acquisition & infra.
Non-persist classes are listed under "NOT in the final set" by disposition.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
INDEX = os.path.join(ROOT, "schemas", "V_eta", "index.json")
OUT = os.path.join(ROOT, "schemas", "V_eta_final_class_set.md")

# The abstract spine & genus (category 1) -- named explicitly; everything else is
# classified by its superclass chain.
SPINE = {
    "app", "base", "data", "data_body", "data_type", "directed_relation", "entity",
    "relation", "subject_assertion", "subject_calculation", "subject_interaction",
    "subject_manipulation", "subject_observation", "subject_statement",
    "undirected_relation",
}


def main():
    idx = json.load(open(INDEX))
    by_name = {s["class_name"]: s for s in idx["schemas"] if not s.get("is_meta")}

    def chain(name, seen=None):
        seen = seen if seen is not None else set()
        s = by_name.get(name)
        if not s:
            return seen
        for sup in s.get("superclasses", []):
            n = sup.get("class_name") if isinstance(sup, dict) else sup
            if n and n not in seen:
                seen.add(n)
                chain(n, seen)
        return seen

    cats = {k: [] for k in
            ("spine", "entity", "composite", "leaf", "timeref", "body", "infra")}
    dropped = {}  # disposition -> [names]
    for name, s in by_name.items():
        if s.get("disposition") != "persist":
            dropped.setdefault(s.get("disposition", "?"), []).append(name)
            continue
        ch = chain(name)
        if name in SPINE:
            cats["spine"].append(name)
        elif "time_reference" in ch or name == "time_reference":
            cats["timeref"].append(name)
        elif "data_body" in ch:
            cats["body"].append(name)
        elif ch & {"subject_observation", "subject_manipulation", "subject_assertion",
                   "subject_calculation"}:
            cats["leaf"].append(name)
        elif "data_type" in ch:
            cats["composite"].append(name)
        elif "entity" in ch:
            cats["entity"].append(name)
        else:
            cats["infra"].append(name)

    for v in cats.values():
        v.sort()
    for v in dropped.values():
        v.sort()
    total = sum(len(v) for v in cats.values())

    def joined(names):
        return ", ".join(f"`{n}`" for n in names)

    lines = []
    lines.append(f"# V_eta — The Final Class Set ({total} persist)")
    lines.append("")
    lines.append("*Generated by `tools/regen_final_class_set.py` from the built "
                 "schema's `index.json` (disposition markers) — do NOT hand-edit; "
                 "re-run after `build_v_eta.py`. Category order: spine → entities → "
                 "composites (data_type) → leaves → time_reference → data_body "
                 "(exactly 2) → infra.*")
    lines.append("")
    lines.append("| Category | n |")
    lines.append("|---|--:|")
    order = [("spine", "① Statement spine & genus"), ("entity", "② Entities"),
             ("composite", "③ Quantity & substance composites (data_type)"),
             ("leaf", "④ Data-type leaf tier"), ("timeref", "⑤ time_reference family"),
             ("body", "⑥ data_body family"),
             ("infra", "⑦ Acquisition & infra (keep)")]
    for key, label in order:
        lines.append(f"| {label} | {len(cats[key])} |")
    lines.append(f"| **Persist total** | **{total}** |")
    lines.append("")
    for key, label in order:
        lines.append(f"## {label} ({len(cats[key])})")
        lines.append(joined(cats[key]) or "*(none)*")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## NOT in the final set (by disposition)")
    lines.append("")
    for disp in sorted(dropped):
        lines.append(f"**{disp} ({len(dropped[disp])}):**")
        lines.append(joined(dropped[disp]))
        lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"regenerated {OUT}: {total} persist "
          f"({', '.join(f'{k}={len(v)}' for k, v in cats.items())}); "
          f"dropped {sum(len(v) for v in dropped.values())} "
          f"({', '.join(f'{k}={len(v)}' for k, v in dropped.items())})")


if __name__ == "__main__":
    main()
