import { useEffect, useMemo, useState } from "react";
import type {
  CoverageRow,
  DecisionFamily,
  DecisionsDoc,
  IndexEntry,
  SchemaDocument,
  TenetRow,
  WalkthroughClass,
  WalkthroughDoc,
} from "./types";
import {
  loadCoverage,
  loadDecisions,
  loadSchema,
  loadTenets,
  loadWalkthrough,
} from "./schemaIndex";
import { FieldsTable } from "./Detail";

// THE PER-CLASS WALKTHROUGH.
//
// The Coverage table answers "what is the fate of every v1 class" one row at a
// time; it cannot answer "what condition is THIS class in", and the fields that
// would settle it were in the ledger all along, rendered by nothing:
//
//     field occurrences in Coverage.tsx before 2026-08-12
//       build_state  0        target_gap  0
//
// This view puts the whole chain on one page, in the order a stranger would ask
// for it: what the source document actually is, what consumes it, what it
// becomes, whether that thing is BUILT, and who signed for it. Every panel
// names where its facts come from, because four different generators feed this
// page and a reader must be able to tell which one to distrust.

interface Props {
  v1Class: string;
  index: IndexEntry[];
  onSelect: (className: string) => void;
  onBack: () => void;
}

const DASH = "—";

export function ClassDetail({ v1Class, index, onSelect, onBack }: Props) {
  const [wt, setWt] = useState<WalkthroughDoc | null>(null);
  const [wtError, setWtError] = useState<string | null>(null);
  const [dec, setDec] = useState<DecisionsDoc | null>(null);
  const [rows, setRows] = useState<CoverageRow[] | null>(null);
  const [tenetRows, setTenetRows] = useState<TenetRow[] | null>(null);

  useEffect(() => {
    let cancelled = false;
    loadWalkthrough()
      .then((d) => !cancelled && setWt(d))
      .catch((e) => !cancelled && setWtError(String(e)));
    loadCoverage()
      .then((d) => !cancelled && setRows(d.rows))
      .catch(() => undefined);
    loadDecisions()
      .then((d) => !cancelled && setDec(d))
      .catch(() => undefined);
    // Non-fatal both ways: the tenet map is context, not evidence about this
    // class, and a bundle without it should still render the walkthrough.
    loadTenets()
      .then((d) => !cancelled && setTenetRows(d.rows))
      .catch(() => undefined);
    return () => {
      cancelled = true;
    };
  }, []);

  const entry = wt?.classes[v1Class] ?? null;
  const row = useMemo(
    () => rows?.find((r) => r.v1_class === v1Class) ?? null,
    [rows, v1Class],
  );
  const fam = useMemo(() => {
    if (!dec || !row) return undefined;
    const key = (row.veta_class && dec.by_class[row.veta_class])
      ?? dec.by_class[row.v1_class];
    return key ? dec.families.find((f) => f.name === key) : undefined;
  }, [dec, row]);

  // Every class this class is claimed to become, from all four ledger slots.
  const targets = useMemo(() => {
    if (!row) return [] as string[];
    const seen = new Set<string>();
    const out: string[] = [];
    for (const t of [...row.targets, ...row.decided_targets,
                     ...row.second_pass, ...row.carried]) {
      if (!seen.has(t)) {
        seen.add(t);
        out.push(t);
      }
    }
    return out;
  }, [row]);

  const tenetsTouching = useMemo(() => {
    if (!tenetRows) return [];
    const names = new Set([v1Class, row?.veta_class ?? "", ...targets]);
    return tenetRows.filter((r) =>
      [...r.before, ...r.after].some((c) => names.has(c)));
  }, [tenetRows, v1Class, row, targets]);

  return (
    <div className="detail class-walkthrough">
      <button className="btn-secondary cw-back" onClick={onBack}>
        ← back to the coverage ledger
      </button>

      <header className="detail-header">
        <h2>
          <code>{v1Class}</code>
          <span className="cw-writer">
            {row?.source === "app" ? "vhlab app class" : "NDI template"}
          </span>
        </h2>
        <p className="registry-description">
          One did_v1 source class, end to end: what NDI declares, what consumes
          it, what it becomes, and whether that has been built.
        </p>
        <StageLadder row={row} />
      </header>

      {rows && !row && (
        <p className="cov-gap-banner">
          No coverage-ledger row for <code>{v1Class}</code>. The ledger is the
          v1 source universe, so a class absent from it is not a v1 source —
          or the served ledger is stale.
        </p>
      )}

      <Step n="1" title="The v1 source, as NDI declares it"
        source="schemas/V_eta_ndi_ground_truth.json — NDI templates + writers, read from origin/main">
        {wtError ? (
          <p className="detail-error">
            Could not load the walkthrough asset: {wtError}
            <span className="section-note">
              {" "}It is generated by <code>tools/gen_class_walkthrough.py</code>{" "}
              into <code>web/public/class_walkthrough.json</code>.
            </span>
          </p>
        ) : !wt ? (
          <p className="detail-loading">Loading…</p>
        ) : (
          <NdiSource entry={entry} v1Class={v1Class} />
        )}
      </Step>

      <Step n="2" title="What consumes it"
        source="a file:line search of DID-matlab +did2/+convert (migrator packages and the batch post-passes)">
        <Consumers entry={entry} row={row} />
      </Step>

      <Step n="3" title="What it becomes"
        source="schemas/V_eta_coverage_ledger.json — targets, decided targets, second pass, carried">
        <Becomes row={row} onSelect={onSelect} />
      </Step>

      <Step n="4" title="Build state, in full"
        source="schemas/V_eta_coverage_ledger.json — build_state, computed by tools/coverage.py">
        <BuildStatePanel row={row} />
      </Step>

      <Step n="5" title="The authored account"
        source="schemas/V_eta_migration_targets.json — `how` and its caveats, via the ledger">
        {row?.how ? (
          <>
            <p className="cw-how">{row.how}</p>
            {row.target_flags && (
              <p className="cw-flags">⚠ {row.target_flags}</p>
            )}
          </>
        ) : (
          <p className="muted">
            No authored account for this class. That is a missing curated row,
            not a statement about the class.
          </p>
        )}
      </Step>

      <Step n="6" title="Decision and sign-off"
        source="schemas/V_eta_decisions.json (tools/status_board.py) + the ledger's own citations">
        <Signoff row={row} fam={fam} />
      </Step>

      <Step n="7" title="The built schema for each target"
        source={`schemas/V_eta — the built tree, read through the set index (${index.length} classes)`}>
        <TargetSchemas targets={targets} index={index} onSelect={onSelect} />
      </Step>

      {tenetsTouching.length > 0 && (
        <Step n="8" title="Tenets that shaped this"
          source="web/public/tenets.json (tools/tenet_map.py) — curated, each row citing a plan document">
          <ul className="cw-tenet-list">
            {tenetsTouching.map((t, i) => (
              <li key={`${t.tenet}-${i}`}>
                <span className="cw-tenet-id">{t.tenet}</span> {t.change}
                <div className="section-note">
                  <code>{t.citation.doc}</code>:{t.citation.line}
                </div>
              </li>
            ))}
          </ul>
        </Step>
      )}
    </div>
  );
}

// Each panel states the artifact its facts come from. Four generators feed this
// page, and "which of these is wrong" is the first question anyone asks when
// two of them disagree.
function Step({ n, title, source, children }: {
  n: string; title: string; source: string; children: React.ReactNode;
}) {
  return (
    <section className="cw-step">
      <h3>
        <span className="cw-step-n">{n}</span> {title}
      </h3>
      <p className="cw-source">source: {source}</p>
      {children}
    </section>
  );
}

// THE DERIVED MIGRATION STAGE, rendered only if the ledger carries one.
//
// Another generator is adding a 0-5 stage ladder to the ledger. Its field shape
// is not settled here, so this renders what it finds and NEVER invents a
// meaning: a number becomes "stage N", an object contributes whatever level and
// label it carries, and anything else is shown raw. An absent stage renders
// NOTHING -- an empty ladder would read as "stage 0", which is a claim.
function StageLadder({ row }: { row: CoverageRow | null }) {
  const stage = row?.stage;
  if (stage === undefined || stage === null) return null;
  if (typeof stage === "number") {
    return (
      <div className="cw-stage">
        <span className="cw-stage-n">stage {stage}</span>
        <span className="section-note">derived migration stage (ledger)</span>
      </div>
    );
  }
  if (typeof stage === "object") {
    const s = stage as Record<string, unknown>;
    const level = s.level ?? s.stage ?? s.n;
    const label = s.label ?? s.name ?? s.title;
    if (level !== undefined || label !== undefined) {
      return (
        <div className="cw-stage">
          {level !== undefined && (
            <span className="cw-stage-n">stage {String(level)}</span>
          )}
          {label !== undefined && <span>{String(label)}</span>}
          {typeof s.reason === "string" && (
            <span className="section-note">{s.reason}</span>
          )}
        </div>
      );
    }
  }
  return (
    <div className="cw-stage">
      <span className="section-note">
        the ledger carries a <code>stage</code> this viewer does not recognise,
        shown raw rather than dropped:
      </span>
      <code>{JSON.stringify(stage)}</code>
    </div>
  );
}

function NdiSource({ entry, v1Class }: {
  entry: WalkthroughClass | null; v1Class: string;
}) {
  if (!entry) {
    return (
      <p className="muted">
        <code>{v1Class}</code> is not in the walkthrough asset. Regenerate it
        with <code>python3 tools/gen_class_walkthrough.py</code>.
      </p>
    );
  }
  const ndi = entry.ndi;
  if (!ndi) {
    return <p className="muted">{entry.ndi_absent_reason}</p>;
  }
  const req = ndi.depends_on_required ?? {};
  return (
    <>
      <dl className="detail-meta">
        <dt>Template</dt>
        <dd><code>{ndi.path ?? DASH}</code></dd>
        <dt>Superclasses</dt>
        <dd>
          {(ndi.superclasses ?? []).length
            ? (ndi.superclasses ?? []).map((s) => (
                <code key={s} className="enum-chip">{s}</code>))
            : <em>none</em>}
        </dd>
        <dt>Schema form</dt>
        <dd>{ndi.schema_document_form ?? DASH}</dd>
      </dl>

      <h4>Fields NDI declares</h4>
      {(ndi.fields ?? []).length === 0 ? (
        <p className="muted">none</p>
      ) : (
        <table className="fields-table cw-ndi-table">
          <thead>
            <tr>
              <th>as V_eta spells it</th>
              <th>as NDI spells it</th>
            </tr>
          </thead>
          <tbody>
            {(ndi.fields ?? []).map((f, i) => (
              <tr key={f}>
                <td><code>{f}</code></td>
                <td><code>{(ndi.raw_fields ?? [])[i] ?? DASH}</code></td>
              </tr>
            ))}
          </tbody>
        </table>
      )}

      <h4>Dependencies NDI declares</h4>
      {(ndi.depends_on ?? []).length === 0 ? (
        <p className="muted">none</p>
      ) : (
        <ul className="kv-list">
          {(ndi.depends_on ?? []).map((d) => (
            <li key={d}>
              <code>{d}</code>{" "}
              {req[d] === true ? (
                <span className="flag-tag">NDI requires it</span>
              ) : req[d] === false ? (
                <span className="muted">optional in NDI</span>
              ) : (
                <span className="muted">NDI states nothing about it</span>
              )}
            </li>
          ))}
        </ul>
      )}

      {(ndi.files ?? []).length > 0 && (
        <>
          <h4>Files</h4>
          <ul className="kv-list">
            {(ndi.files ?? []).map((f) => (
              <li key={f}><code>{f}</code></li>
            ))}
          </ul>
        </>
      )}

      {/* WHERE TEMPLATE AND WRITER DISAGREE, THE WRITER WINS. That rule is the
          whole ground-truth track, and a reader looking at the template alone
          would take the losing side. */}
      {entry.writer_divergence.length > 0 && (
        <div className="cw-warn">
          <strong>The template and the writer disagree — the writer wins.</strong>
          {entry.writer_divergence.map((w, i) => (
            <dl className="detail-meta" key={i}>
              <dt>template says</dt><dd>{w.template_says}</dd>
              <dt>writer emits</dt><dd>{w.writer_emits}</dd>
              <dt>writer</dt><dd><code>{w.writer}</code></dd>
              {w.note && <><dt>note</dt><dd>{w.note}</dd></>}
            </dl>
          ))}
        </div>
      )}

      {entry.v_alpha_divergence && (
        <div className="cw-warn">
          <strong>
            Our own V_alpha snapshot differs from the NDI template
            {entry.v_alpha_divergence.provenance?.verdict
              ? ` — ${entry.v_alpha_divergence.provenance.verdict}`
              : ""}.
          </strong>
          <ul className="kv-list">
            <li>
              only in our snapshot:{" "}
              {(entry.v_alpha_divergence.only_in_our_snapshot ?? []).length
                ? (entry.v_alpha_divergence.only_in_our_snapshot ?? [])
                    .map((f) => <code key={f} className="enum-chip">{f}</code>)
                : <span className="muted">none</span>}
            </li>
            <li>
              only in the NDI template:{" "}
              {(entry.v_alpha_divergence.only_in_ndi_template ?? []).length
                ? (entry.v_alpha_divergence.only_in_ndi_template ?? [])
                    .map((f) => <code key={f} className="enum-chip">{f}</code>)
                : <span className="muted">none</span>}
            </li>
            {entry.v_alpha_divergence.provenance?.why && (
              <li className="section-note">
                {entry.v_alpha_divergence.provenance.why}
              </li>
            )}
          </ul>
        </div>
      )}

      {entry.migrator_reads.length > 0 && (
        <div className="cw-warn">
          <strong>
            A migrator reads field names no real document has.
          </strong>
          {entry.migrator_reads.map((m, i) => (
            <ul className="kv-list" key={i}>
              <li>
                <code>{m.migrator}</code>{" "}
                <span className="flag-tag">{m.confidence}</span>
              </li>
              <li>
                reads, absent from the template:{" "}
                {(m.reads_names_absent_from_template ?? []).map((f) => (
                  <code key={f} className="enum-chip">{f}</code>))}
              </li>
            </ul>
          ))}
        </div>
      )}
    </>
  );
}

function Consumers({ entry, row }: {
  entry: WalkthroughClass | null; row: CoverageRow | null;
}) {
  if (!entry) return <p className="muted">Walkthrough asset not loaded.</p>;
  const migs = entry.consumers.per_class_migrators;
  const mentions = entry.consumers.convert_package_mentions;
  return (
    <>
      <h4>Per-class migrator</h4>
      {migs.length === 0 ? (
        <p className="muted">
          No file named after this class in any convert package.
          {row?.migrator
            ? " The ledger says a migrator consumes it, so one of the two is"
              + " wrong — the generator reports every such disagreement."
            : " The ledger agrees. Where that is the design rather than a gap,"
              + " a batch post-pass handles the class and the account in step 5"
              + " says so."}
        </p>
      ) : (
        <ul className="kv-list">
          {migs.map((m) => (
            <li key={m.path}>
              <code>{m.path}</code>{" "}
              <span className="flag-tag">{m.package}</span>
              {m.spelling !== row?.v1_class && (
                <span className="section-note">
                  {" "}named in the V_eta spelling (<code>{m.spelling}</code>),
                  not the NDI one
                </span>
              )}
            </li>
          ))}
        </ul>
      )}

      <h4>Named in the convert package</h4>
      <p className="section-note">
        Evidence, not a claim: a name can appear in a comment, an allow-list or
        an error message. Which passes run, and in what order, is the corpus
        harness's fact and is not derivable from this repository.
      </p>
      {mentions.length === 0 ? (
        <p className="muted">No convert-package file names this class.</p>
      ) : (
        mentions.map((m) => (
          <details key={m.path} className="cw-mentions">
            <summary>
              <code>{m.pass}</code> — {m.site_count} site
              {m.site_count === 1 ? "" : "s"}
            </summary>
            <ul className="kv-list">
              {m.sites.map((s) => (
                <li key={`${m.path}:${s.line}`}>
                  <code>
                    {m.path}:{s.line}
                  </code>
                  <div className="cw-code-line">{s.text}</div>
                </li>
              ))}
            </ul>
          </details>
        ))
      )}
    </>
  );
}

// The five ledger slots that answer "what does it become", each with the thing
// that distinguishes it from the others. They were rendered as one chip row for
// a long time, which made a DECIDED target and an EMITTED one read the same.
const TARGET_SOURCE_MEANING: Record<string, string> = {
  emitted: "measured from the migrators: these classes are what pass 1 emits.",
  decided: "the team signed this disposition and NO migrator implements it yet."
    + " The document passes through untouched today.",
  passthrough: "no migrator consumes this class, so its documents reach"
    + " validation under the same-name V_eta class. That is what happens"
    + " today; it is NOT a record of where the class is going.",
  uncurated: "a migrator runs, and nothing records what it emits. A missing"
    + " curated row, not an open modelling question.",
  unknown: "no migrator and no same-name class to land on.",
};

function Becomes({ row, onSelect }: {
  row: CoverageRow | null; onSelect: (c: string) => void;
}) {
  if (!row) return <p className="muted">No ledger row.</p>;
  const chip = (c: string, cls: string) => (
    <button key={cls + c} className={`cov-link enum-chip ${cls}`}
      onClick={() => onSelect(c)} title={`Open ${c}`}>
      {c}
    </button>
  );
  return (
    <>
      <p className="cw-target-source">
        <strong>{row.target_source}</strong>{" "}
        — {TARGET_SOURCE_MEANING[row.target_source] ?? "unrecognised source."}
      </p>
      <dl className="detail-meta">
        <dt>emitted in pass 1</dt>
        <dd>{row.targets.length
          ? row.targets.map((t) => chip(t, "cov-target-emit"))
          : <span className="muted">{DASH}</span>}</dd>
        <dt>decided, not yet emitted</dt>
        <dd>{row.decided_targets.length
          ? row.decided_targets.map((t) => chip(t, "cov-target-decided"))
          : <span className="muted">{DASH}</span>}</dd>
        <dt>minted in the NDI second pass</dt>
        <dd>{row.second_pass.length
          ? row.second_pass.map((t) => chip(t, "cov-target-2pass"))
          : <span className="muted">{DASH}</span>}</dd>
        <dt>carried (pre-existing, attached to)</dt>
        <dd>{row.carried.length
          ? row.carried.map((t) => chip(t, "cov-target-carried"))
          : <span className="muted">{DASH}</span>}</dd>
      </dl>

      {/* target_gap: NARROWER than the retired `gap`, and rendered by nothing
          until now. "No target and no dissolution recorded" is a gap in the
          RECORD; it does not mean the class is unhandled. */}
      {row.target_gap && (
        <p className="cov-gap-banner">
          ⚠ <strong>target gap</strong> — no target and no dissolution recorded.
          A gap in the record, not a decision.
          {row.no_target_reason_label
            ? ` Reason recorded: ${row.no_target_reason_label}`
            : " No reason recorded."}
        </p>
      )}
      {!row.target_gap && row.no_target_reason_label && (
        <p className="section-note">
          Why there is no target: {row.no_target_reason_label}
        </p>
      )}
      {row.no_target_account && (
        <p className="cw-how">{row.no_target_account}</p>
      )}
    </>
  );
}

// BUILD STATE, IN FULL. Two independent halves and the ledger keeps them apart
// on purpose: `schema_targets_built` is a fact about this repository,
// `migrator_emits_decided_targets` is a fact about DID-matlab, and for several
// classes exactly one of them is true. Summing them into one "done" light is
// the thing this panel exists to refuse.
function BuildStatePanel({ row }: { row: CoverageRow | null }) {
  const bs = row?.build_state;
  if (!bs) {
    return (
      <p className="muted">
        This ledger carries no <code>build_state</code> for this class. Absent,
        not empty — regenerate with <code>python3 tools/coverage.py</code>.
      </p>
    );
  }
  return (
    <table className="fields-table cw-build-table">
      <tbody>
        <tr>
          <th>schema targets named</th>
          <td>{bs.schema_targets_named}</td>
          <td className="doc-cell">
            How many V_eta classes the decision names. 0 means the decision
            names none — which is an answer for a dissolution.
          </td>
        </tr>
        <tr>
          <th>schema targets BUILT</th>
          <td>
            {bs.schema_targets_built.length
              ? bs.schema_targets_built.map((c) => (
                  <code key={c} className="enum-chip">{c}</code>))
              : <span className="muted">{DASH}</span>}
          </td>
          <td className="doc-cell">
            Present in the built <code>schemas/V_eta</code> tree. A fact about
            this repository only.
          </td>
        </tr>
        <tr className={bs.schema_targets_missing.length ? "cov-row-gap" : ""}>
          <th>schema targets MISSING</th>
          <td>
            {bs.schema_targets_missing.length
              ? bs.schema_targets_missing.map((c) => (
                  <code key={c} className="enum-chip">{c}</code>))
              : <span className="muted">none</span>}
          </td>
          <td className="doc-cell">
            Named by the decision and absent from the built tree. This is the
            outstanding schema work, and it is the half a green corpus run
            cannot see.
          </td>
        </tr>
        <tr>
          <th>migrator emits the decided targets</th>
          <td>{bs.migrator_emits_decided_targets ? "yes" : "no"}</td>
          <td className="doc-cell">
            A fact about DID-matlab, independent of the row above. A schema can
            be built with nothing emitting it, and a migrator can emit a class
            the decision has since renamed.
          </td>
        </tr>
        <tr>
          <th>has a per-class migrator</th>
          <td>{bs.has_per_class_migrator ? "yes" : "no"}</td>
          <td className="doc-cell">
            A file named after this class in a convert package. `no` is
            sometimes the design: several classes are handled by a batch
            post-pass and will never have one.
          </td>
        </tr>
      </tbody>
    </table>
  );
}

function Signoff({ row, fam }: {
  row: CoverageRow | null; fam: DecisionFamily | undefined;
}) {
  const cites = [
    ["decided targets recorded in", row?.decided_targets_source],
    ["sign-off for the decided targets", row?.decided_signoff],
    ["sign-off for having no target", row?.no_target_signoff],
  ].filter(([, v]) => Boolean(v)) as Array<[string, string]>;

  if (!fam && cites.length === 0) {
    return (
      <p className="muted">
        No decision family claims this class and the ledger cites no sign-off.
        For most classes that is correct — they are settled and need no marker.
      </p>
    );
  }
  return (
    <>
      {fam && (
        <div className={`decision-banner ${
          fam.state === "signed_awaiting_build" ? ""
            : fam.state === "awaiting_signature" ? "decision-unsigned"
              : "decision-proposed"}`}>
          <div className="decision-banner-head">
            {fam.state_label} · <code>{fam.name}</code>
          </div>
          <div>{fam.decision}</div>
          {fam.plan && (
            <div className="section-note">
              Recorded in <code>schemas/{fam.plan}</code>
            </div>
          )}
          {fam.signoff && (
            <div className="decision-banner-signoff">
              TEAM-SIGN-OFF: {fam.signoff}
            </div>
          )}
        </div>
      )}
      {cites.length > 0 && (
        <dl className="detail-meta">
          {cites.map(([k, v]) => (
            <div key={k} style={{ display: "contents" }}>
              <dt>{k}</dt>
              <dd>{v}</dd>
            </div>
          ))}
        </dl>
      )}
    </>
  );
}

function TargetSchemas({ targets, index, onSelect }: {
  targets: string[]; index: IndexEntry[]; onSelect: (c: string) => void;
}) {
  if (targets.length === 0) {
    return (
      <p className="muted">
        This class names no target, in any slot. Step 3 says whether that is a
        recorded dissolution or a gap.
      </p>
    );
  }
  const byName = new Map(index.map((e) => [e.class_name, e]));
  return (
    <>
      {targets.map((t) => {
        const entry = byName.get(t);
        return entry ? (
          <TargetSchema key={t} entry={entry} onSelect={onSelect} />
        ) : (
          <div key={t} className="cw-warn">
            <strong><code>{t}</code> is NOT in the built schema set.</strong>{" "}
            The ledger names it as a target and the tree does not carry it —
            either it is decided and unbuilt, or the served schema set is a
            different version from the served ledger.
          </div>
        );
      })}
    </>
  );
}

function TargetSchema({ entry, onSelect }: {
  entry: IndexEntry; onSelect: (c: string) => void;
}) {
  const [doc, setDoc] = useState<SchemaDocument | null>(null);
  const [err, setErr] = useState<string | null>(null);
  useEffect(() => {
    let cancelled = false;
    loadSchema(entry)
      .then((d) => !cancelled && setDoc(d))
      .catch((e) => !cancelled && setErr(String(e)));
    return () => {
      cancelled = true;
    };
  }, [entry.class_name, entry.path]);

  return (
    <details className="cw-target-schema" open>
      <summary>
        <code>{entry.class_name}</code>
        <span className={`maturity-${entry.maturity_level ?? "meta"}`}>
          {entry.maturity_level ?? "meta"}
        </span>
        {entry.disposition === "retire" && (
          <span className="badge-retire">retire</span>
        )}
        {entry.disposition === "in_progress" && (
          <span className="badge-wip">wip</span>
        )}
        <button className="cov-link" onClick={(e) => {
          e.preventDefault();
          onSelect(entry.class_name);
        }}>open full schema →</button>
      </summary>
      {err && <p className="detail-error">{err}</p>}
      {!doc && !err && <p className="detail-loading">Loading schema…</p>}
      {doc && (
        <>
          <p className="section-note">
            <code>{entry.path}</code>
            {doc.document_class?.superclasses?.length
              ? ` · ⊂ ${doc.document_class.superclasses
                  .map((s) => (typeof s === "string" ? s : s.class_name))
                  .join(", ")}`
              : ""}
          </p>
          {doc.fields && doc.fields.length > 0 ? (
            <FieldsTable fields={doc.fields} />
          ) : (
            <p className="muted">This class declares no fields of its own.</p>
          )}
          {doc.depends_on && doc.depends_on.length > 0 && (
            <>
              <h4>Depends on</h4>
              <ul className="kv-list">
                {doc.depends_on.map((d) => (
                  <li key={d.name}>
                    <code>{d.name}</code>
                    {d.mustBeNonEmpty && (
                      <span className="flag-tag">mustBeNonEmpty</span>
                    )}
                    {d.documentation && (
                      <div className="docline">{d.documentation}</div>
                    )}
                  </li>
                ))}
              </ul>
            </>
          )}
          {doc.file && doc.file.length > 0 && (
            <>
              <h4>Files</h4>
              <ul className="kv-list">
                {doc.file.map((f) => (
                  <li key={f.name}><code>{f.name}</code></li>
                ))}
              </ul>
            </>
          )}
        </>
      )}
    </details>
  );
}
