import { useEffect, useMemo, useState } from "react";
import type { CoverageLedger, CoverageRow } from "./types";
import { loadCoverage } from "./schemaIndex";

interface Props {
  // Jump to a class's detail view (used by the clickable V_eta class chip).
  onSelect: (className: string) => void;
}

const DASH = "—";

// Coarse category for a row, used for both the badge style and the filter chips.
// The generated ledger puts settled classes on `persist`/`retire`/`in_progress`
// and everything else on a descriptive string ("UNMAPPED ...", "dissolved ...",
// "test/demo ..."), so key off the structured flags first, then the disposition.
type Kind = "persist" | "retire" | "in_progress" | "dissolved" | "unmapped" | "nonprod";

function kindOf(r: CoverageRow): Kind {
  if (r.gap) return "unmapped";
  if (r.nonprod) return "nonprod";
  if (r.disposition === "persist") return "persist";
  if (r.disposition === "retire") return "retire";
  if (r.disposition === "in_progress") return "in_progress";
  return "dissolved";
}

const KIND_META: Record<Kind, { label: string; cls: string; tip: string }> = {
  persist: { label: "persist", cls: "cov-persist", tip: "settled go-forward V_eta class" },
  retire: { label: "retire", cls: "cov-retire", tip: "carried but dissolving; not in final set" },
  in_progress: { label: "in progress", cls: "cov-wip", tip: "carried; ⑥/⑦ disposition not finalized" },
  dissolved: { label: "dissolved", cls: "cov-dissolved", tip: "folded into another class by rename/decomposition" },
  unmapped: { label: "unmapped", cls: "cov-gap", tip: "no V_eta home, no migrator, never reviewed — an actionable hole" },
  nonprod: { label: "test/demo", cls: "cov-nonprod", tip: "NDI test/demo scaffolding, not real corpus data" },
};

const KIND_ORDER: Kind[] = [
  "unmapped", "in_progress", "retire", "persist", "dissolved", "nonprod",
];

export function Coverage({ onSelect }: Props) {
  const [led, setLed] = useState<CoverageLedger | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [q, setQ] = useState("");
  const [activeKinds, setActiveKinds] = useState<Set<Kind>>(new Set(KIND_ORDER));
  const [source, setSource] = useState<"all" | "ndi" | "app">("all");

  useEffect(() => {
    let cancelled = false;
    loadCoverage()
      .then((l) => !cancelled && setLed(l))
      .catch((e) => !cancelled && setError(String(e)));
    return () => {
      cancelled = true;
    };
  }, []);

  const toggleKind = (k: Kind) =>
    setActiveKinds((prev) => {
      const next = new Set(prev);
      if (next.has(k)) next.delete(k);
      else next.add(k);
      return next;
    });

  const rows = led?.rows ?? [];
  const kindCounts = useMemo(() => {
    const c = {} as Record<Kind, number>;
    for (const k of KIND_ORDER) c[k] = 0;
    for (const r of rows) c[kindOf(r)]++;
    return c;
  }, [rows]);

  const filtered = useMemo(() => {
    const needle = q.trim().toLowerCase();
    return rows.filter((r) => {
      if (!activeKinds.has(kindOf(r))) return false;
      if (source !== "all" && r.source !== source) return false;
      if (needle) {
        const hay = `${r.v1_class} ${r.veta_class ?? ""} ${r.disposition}`.toLowerCase();
        if (!hay.includes(needle)) return false;
      }
      return true;
    });
  }, [rows, activeKinds, source, q]);

  if (error) {
    return (
      <div className="detail">
        <div className="detail-error">
          Could not load coverage ledger: {error}
          <p className="section-note">
            It is generated by <code>tools/coverage.py</code> and copied to{" "}
            <code>public/coverage.json</code> by <code>npm run sync-schemas</code>.
          </p>
        </div>
      </div>
    );
  }
  if (!led) return <div className="detail-loading">Loading coverage ledger…</div>;

  const s = led.summary;

  return (
    <div className="detail coverage">
      <header className="detail-header">
        <h2>{led.title}</h2>
        <p className="registry-description">{led.description}</p>
        <div className="cov-stats">
          <Stat n={s.total} label="v1 source classes" />
          <Stat n={s.by_source.ndi ?? 0} label="NDI / main" />
          <Stat n={s.by_source.app ?? 0} label="vhlab app" />
          <Stat n={s.with_migrator} label="bespoke migrator" />
          <Stat n={s.gaps} label="unmapped" warn={s.gaps > 0} />
        </div>
        {s.gaps > 0 && (
          <p className="cov-gap-banner">
            ⚠ {s.gaps} class{s.gaps === 1 ? "" : "es"} on NDI/main have no V_eta home
            yet — filter to <strong>unmapped</strong> below to see them.
          </p>
        )}
      </header>

      <div className="cov-controls">
        <input
          className="cov-search"
          type="search"
          placeholder="Filter by class name…"
          value={q}
          onChange={(e) => setQ(e.target.value)}
        />
        <div className="cov-kind-chips" role="group" aria-label="Filter by fate">
          {KIND_ORDER.map((k) => {
            const on = activeKinds.has(k);
            const m = KIND_META[k];
            return (
              <button
                key={k}
                type="button"
                className={`cov-chip ${m.cls} ${on ? "" : "cov-chip-off"}`}
                aria-pressed={on}
                title={`${m.tip} — click to ${on ? "hide" : "show"}`}
                onClick={() => toggleKind(k)}
              >
                {m.label} <span className="cov-chip-n">{kindCounts[k]}</span>
              </button>
            );
          })}
        </div>
        <div className="cov-source-toggle" role="group" aria-label="Filter by writer">
          {(["all", "ndi", "app"] as const).map((sv) => (
            <button
              key={sv}
              type="button"
              className={source === sv ? "active" : ""}
              onClick={() => setSource(sv)}
              title={
                sv === "ndi"
                  ? "NDI production templates"
                  : sv === "app"
                    ? "vhlab app/calculator classes (no NDI template)"
                    : "both writers"
              }
            >
              {sv === "all" ? "all writers" : sv === "ndi" ? "NDI" : "vhlab app"}
            </button>
          ))}
        </div>
      </div>

      <p className="section-note">
        Showing {filtered.length} of {rows.length}. The <strong>V_eta class</strong>{" "}
        column links to the class definition when a same-named class exists.
      </p>

      <table className="fields-table cov-table">
        <thead>
          <tr>
            <th>v1 class</th>
            <th>V_eta class</th>
            <th>fate</th>
            <th>migrator</th>
            <th>writer</th>
          </tr>
        </thead>
        <tbody>
          {filtered.map((r) => {
            const kind = kindOf(r);
            const m = KIND_META[kind];
            return (
              <tr key={r.v1_class} className={r.gap ? "cov-row-gap" : ""}>
                <td>
                  <code>{r.v1_class}</code>
                </td>
                <td>
                  {r.veta_class ? (
                    <>
                      <button
                        className={`cov-link enum-chip cov-target-${kind}`}
                        onClick={() => onSelect(r.veta_class!)}
                        title={
                          kind === "retire"
                            ? `${r.veta_class} is retiring (tombstone until Phase-8 deletion) — not a go-forward home`
                            : `Open ${r.veta_class}`
                        }
                      >
                        {r.veta_class}
                      </button>
                      {kind === "retire" && (
                        <span className="cov-target-note" title="dissolving; kept until Phase-8 deletion">
                          {" "}retiring
                        </span>
                      )}
                    </>
                  ) : (
                    <span className="muted">{DASH}</span>
                  )}
                </td>
                <td>
                  <span className={`cov-badge ${m.cls}`} title={m.tip}>
                    {m.label}
                  </span>
                  {kind === "dissolved" && r.disposition.includes("→") && (
                    <span className="cov-dissolved-target">
                      {" "}
                      {r.disposition.replace(/^dissolved\s*/, "")}
                    </span>
                  )}
                </td>
                <td>
                  {r.migrator ? (
                    <span className="cov-yes">yes</span>
                  ) : (
                    <span className="muted">{DASH}</span>
                  )}
                </td>
                <td>
                  <span className="cov-writer">{r.source === "app" ? "vhlab" : "NDI"}</span>
                </td>
              </tr>
            );
          })}
          {filtered.length === 0 && (
            <tr>
              <td colSpan={5} className="muted">
                No classes match the current filters.
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
}

function Stat({ n, label, warn }: { n: number; label: string; warn?: boolean }) {
  return (
    <div className={`cov-stat ${warn ? "cov-stat-warn" : ""}`}>
      <span className="cov-stat-n">{n}</span>
      <span className="cov-stat-label">{label}</span>
    </div>
  );
}
