import { useEffect, useMemo, useState } from "react";
import type { TenetRow, TenetsDoc } from "./types";
import { loadTenets } from "./schemaIndex";

// BRAINSTORM J'S 14 TENETS, AND THE CLASSES EACH ONE SHAPED.
//
// The tenets are the design rationale for the whole migration and the link from
// a tenet to a class existed only in prose: 353 T-references across
// schemas/*.md, and 0 of 245 built schema files name a tenet at all. So the map
// is CURATED (tools/tenet_map.py) and every row arrives with the plan document
// and the verbatim line that substantiates it -- shown, not hidden behind a
// tooltip, because the citation is the only reason to believe the row.
//
// Two things this panel refuses to do:
//   * render a tenet with no rows as an empty box. An unmapped tenet and a
//     tenet that shaped nothing look identical that way, and only one of them
//     is a fact about the project.
//   * draw a decided-but-unbuilt class the same as a built one. `after` chips
//     carry their register, so `acquisition_layout` cannot read as shipped.

interface Props {
  // Open a built V_eta class in the schema detail view.
  onSelect: (className: string) => void;
  // Open a did_v1 source class in the per-class walkthrough.
  onOpenClass: (v1Class: string) => void;
}

export function Tenets({ onSelect, onOpenClass }: Props) {
  const [doc, setDoc] = useState<TenetsDoc | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [open, setOpen] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    loadTenets()
      .then((d) => !cancelled && setDoc(d))
      .catch((e) => !cancelled && setError(String(e)));
    return () => {
      cancelled = true;
    };
  }, []);

  const byTenet = useMemo(() => {
    const m = new Map<string, TenetRow[]>();
    for (const r of doc?.rows ?? []) {
      if (!m.has(r.tenet)) m.set(r.tenet, []);
      m.get(r.tenet)!.push(r);
    }
    return m;
  }, [doc]);

  if (error) {
    return (
      <div className="detail">
        <div className="detail-error">
          Could not load the tenet map: {error}
          <p className="section-note">
            It is generated by <code>tools/tenet_map.py</code> into{" "}
            <code>web/public/tenets.json</code>.
          </p>
        </div>
      </div>
    );
  }
  if (!doc) return <div className="detail-loading">Loading tenets…</div>;

  const d = doc.denominator;
  return (
    <div className="detail tenets">
      <header className="detail-header">
        <h2>{doc.title}</h2>
        <p className="registry-description">{doc.description}</p>
        <div className="cov-stats">
          <Stat n={d.tenets_declared} label="tenets" />
          <Stat n={d.tenets_with_at_least_one_row} label="with a mapping" />
          <Stat n={d.rows} label="substantiated rows" />
          <Stat n={d.distinct_classes_named} label="classes named" />
          <Stat n={d.plan_documents_cited.length} label="plan docs cited" />
          <Stat
            n={d.tenets_with_no_substantiated_row.length}
            label="unmapped"
            warn={d.tenets_with_no_substantiated_row.length > 0}
          />
        </div>
        <p className="section-note">
          {d.classes_that_are_v1_sources} of the named classes are did_v1
          sources and {d.classes_in_the_built_set} are in the built V_eta set.{" "}
          {d.classes_vouched_only_by_the_cited_plan.length > 0 && (
            <>
              {d.classes_vouched_only_by_the_cited_plan.length} are vouched for
              by the cited plan alone — decided-but-unbuilt, or superseded:{" "}
              {d.classes_vouched_only_by_the_cited_plan.map((c) => (
                <code key={c} className="enum-chip cw-plan-only">{c}</code>
              ))}
            </>
          )}
        </p>
        <p className="section-note">
          Negative control: {d.negative_control}.
        </p>
      </header>

      {doc.tenets.map((t) => {
        const rows = byTenet.get(t.id) ?? [];
        const isOpen = open === t.id;
        return (
          <section key={t.id} className="tenet-block">
            <h3>
              <span className="tenet-id">{t.id}</span> {t.title}
            </h3>
            <button
              className="btn-secondary tenet-toggle"
              onClick={() => setOpen(isOpen ? null : t.id)}
              aria-expanded={isOpen}
            >
              {isOpen ? "hide the tenet as written" : "read the tenet as written"}
            </button>
            {isOpen && (
              <pre className="tenet-statement">{t.statement}</pre>
            )}

            {rows.length === 0 ? (
              // NAMED, not blank. See the header comment.
              <p className="cov-gap-banner">
                No substantiated mapping for {t.id}. That is a statement about
                the map, not about the tenet: nothing in{" "}
                <code>{doc.tenets_document}</code> or the plan documents was
                found that ties {t.id} to specific classes with a citation.
              </p>
            ) : (
              rows.map((r, i) => (
                <TenetRowView
                  key={`${t.id}-${i}`}
                  row={r}
                  onSelect={onSelect}
                  onOpenClass={onOpenClass}
                />
              ))
            )}
          </section>
        );
      })}
    </div>
  );
}

function TenetRowView({ row, onSelect, onOpenClass }: {
  row: TenetRow;
  onSelect: (c: string) => void;
  onOpenClass: (c: string) => void;
}) {
  // A chip's LOOK carries its REGISTER, and the register comes from the
  // artifact rather than being re-derived here: tools/tenet_map.py already
  // checked every name against the v1 source universe, the built schema set and
  // the cited document, and recorded which vouched for it. Drawing a
  // decided-but-unbuilt target the same as a shipped class is the single most
  // misleading thing this panel could do in front of a reader deciding what is
  // finished.
  const chip = (c: string, side: "before" | "after") => {
    const where = row.class_registers[c] ?? [];
    const planOnly = row.plan_only_classes.includes(c);
    const built = where.includes("built");
    const isV1 = where.includes("v1_source");
    const cls = planOnly
      ? "cw-plan-only"
      : side === "before"
        ? "tenet-chip-before"
        : "tenet-chip-after";
    const title = planOnly
      ? `${c}: named in ${row.citation.doc} only — not a v1 source and not in `
        + "the built V_eta set (decided-but-unbuilt, or superseded)"
      : `${c}: ${[built && "in the built V_eta set",
                  isV1 && "a did_v1 source class"]
        .filter(Boolean).join("; ")}`;
    // A v1 source that is not itself a built class opens the walkthrough (its
    // fate is the interesting thing); anything built opens its schema.
    const open = () => (isV1 && !built ? onOpenClass(c) : onSelect(c));
    return (
      <button key={side + c} className={`cov-link enum-chip ${cls}`}
        title={title} onClick={open} disabled={planOnly && !built}>
        {c}
        {planOnly && <span className="tenet-chip-mark">◇</span>}
      </button>
    );
  };

  return (
    <div className="tenet-row">
      <p className="tenet-change">{row.change}</p>
      <div className="tenet-ba">
        <div className="tenet-ba-side">
          <span className="tenet-ba-label">did_v1</span>
          {row.before.map((c) => chip(c, "before"))}
        </div>
        <div className="tenet-arrow">→</div>
        <div className="tenet-ba-side">
          <span className="tenet-ba-label">V_eta</span>
          {row.after.map((c) => chip(c, "after"))}
        </div>
      </div>
      {row.after_not_built.length > 0 && (
        <p className="tenet-unbuilt">
          Not built yet:{" "}
          {row.after_not_built.map((c) => (
            <code key={c} className="enum-chip">{c}</code>
          ))}{" "}
          — decided, and absent from the built schema set.
        </p>
      )}
      {row.note && <p className="tenet-note">{row.note}</p>}
      <blockquote className="tenet-citation">
        <div className="tenet-citation-quote">{row.citation.quote}</div>
        <div className="tenet-citation-src">
          <code>{row.citation.doc}</code>:{row.citation.line}
        </div>
      </blockquote>
    </div>
  );
}

function Stat({ n, label, warn }: { n: number; label: string; warn?: boolean }) {
  return (
    <div className={`cov-stat ${warn ? "cov-stat-warn" : ""}`}>
      <span className="cov-stat-n">{n}</span>
      <span className="cov-stat-label">{label}</span>
    </div>
  );
}
