export type Tier = "stable" | "draft" | "deprecated";
export type Maturity = "stable" | "draft" | "deprecated" | null;
// Migration disposition (written into index.json by build_v_eta.py):
//   persist     — settled go-forward class (in the final V1 set)
//   retire      — decided to dissolve/delete; not in final V1 (see disposition_note)
//   in_progress — persists but its ⑥/⑦ disposition is not yet finalized
export type Disposition = "persist" | "retire" | "in_progress";

export interface IndexEntry {
  class_name: string;
  tier: Tier;
  class_version: string | null;
  maturity_level: Maturity;
  superclasses: string[];
  path: string;
  is_meta?: boolean;
  disposition?: Disposition;
  disposition_note?: string;
}

export interface SchemaIndex {
  set_version: string;
  schema_version_value: string;
  based_on?: string;
  tiers: Tier[];
  notes?: string;
  schemas: IndexEntry[];
}

// Manifest of the schema sets available to the viewer, written by
// scripts/sync-schemas.mjs. `default` is the set shown on first load.
export interface VersionsManifest {
  versions: string[];
  default: string;
}

// V_eta migration coverage ledger (generated by tools/coverage.py, served as
// public/coverage.json). One row per did_v1 SOURCE class with its V_eta fate.
export interface CoverageRow {
  v1_class: string;
  veta_class: string | null; // null => no same-name V_eta class (dissolved/unmapped)
  disposition: string; // persist | retire | in_progress | a dissolved/unmapped label
  migrator: boolean; // a bespoke migrator consumes it (else base/passthrough)
  source: "ndi" | "app"; // NDI production template vs vhlab app/calculator class
  nonprod: boolean; // NDI test/demo scaffolding, not real corpus data
  gap: boolean; // no V_eta home, no migrator, never reviewed -> actionable hole
  // Migration TARGETS: the V_eta document class(es) the migrator emits.
  targets: string[]; // pass-1 emitted classes (or [same-name] for passthrough/rename)
  carried: string[]; // pre-existing classes the emitted statements attach to (not minted)
  second_pass: string[]; // classes minted in the NDI second pass
  how: string; // one-line authored intent
  target_flags: string; // caveats: dynamic emit, header/code mismatch, deferrals
}

export interface CoverageSummary {
  total: number;
  by_disposition: Record<string, number>;
  by_source: Record<string, number>;
  with_migrator: number;
  gaps: number;
}

export interface CoverageLedger {
  title: string;
  description: string;
  summary: CoverageSummary;
  rows: CoverageRow[];
}

// ---- Decision families (schemas/V_eta_decisions.json, generated by
// tools/status_board.py) --------------------------------------------------
//
// The ledger says what a class's DISPOSITION is; this says whether the model
// behind it has been DECIDED. Those are different facts, and the viewer showed
// only the first: a signed, settled family whose build is queued rendered as
// `in_progress`, which reads as "nobody has decided this yet".
export type DecisionState =
  | "signed_awaiting_build"
  | "awaiting_signature"
  | "proposed_unreviewed"
  | "open";

export interface DecisionMember {
  class_name: string;
  disposition: string; // the class's own state; may already be built
}

export interface DecisionFamily {
  name: string;
  members: DecisionMember[];
  open_members: string[];
  plan: string | null;
  decision: string;
  status: "team" | "proposed" | "open";
  signed: boolean;
  signoff: string | null;
  state: DecisionState;
  state_label: string;
}

export interface DecisionsDoc {
  title: string;
  description: string;
  summary: {
    families: number;
    classes_claimed: number;
    open_classes: number;
    by_state: Record<DecisionState, number>;
    state_labels: Record<DecisionState, string>;
  };
  families: DecisionFamily[];
  by_class: Record<string, string>; // class name -> family name
}

// Topic tree (purely a viewer affordance). Lives in
// schemas/V_delta/topics.json. Interior nodes have a `name`; leaves are
// referenced by class_name in `classes`. Children may be omitted.
export interface TopicCategory {
  name: string;
  description?: string;
  classes?: string[];
  children?: TopicCategory[];
}

export interface TopicsFile {
  set_version: string;
  notes?: string;
  // Top-level bare leaf classes (rendered without a folder at the root of
  // the topic tree). Example: `base`.
  classes?: string[];
  topics: TopicCategory[];
}

export interface FieldDef {
  name: string;
  type: string;
  blank_value?: unknown;
  default_value?: unknown;
  mustBeNonEmpty?: boolean;
  mustBeScalar?: boolean;
  mustNotHaveNaN?: boolean;
  queryable?: boolean;
  ontology?: { node?: string; name?: string } | null;
  documentation?: string;
  constraints?: Record<string, unknown> | null;
  fields?: FieldDef[];
}

export interface DependsOnEntry {
  name: string;
  mustBeNonEmpty?: boolean;
  documentation?: string;
}

export interface FileEntry {
  name: string;
  documentation?: string;
}

export interface SchemaDocument {
  document_class?: {
    class_name: string;
    class_version?: string;
    superclasses?: SuperclassRef[];
    maturity_level?: Maturity;
  };
  depends_on?: DependsOnEntry[];
  file?: FileEntry[];
  fields?: FieldDef[];
  // Meta-schemas and registries may have arbitrary other shapes; keep open.
  [key: string]: unknown;
}

// The binding registry meta-file (schemas/V_*/stable/binding_registry_meta.json).
// Maps a statement's `variable` to the admissible value_set for its term value,
// and declares the kind-defining variables whose presence marks a subject's kind
// (D9). Only present from V_eta on; absent sets simply have no registry to browse.
// An ontology node reference: a CURIE plus a human-readable label snapshot.
export interface NodeRef {
  node: string;
  name: string;
}

// A subject_statement binding: variable (+ method) -> the concrete leaf `class`
// that carries the statement. The leaf fixes the value type (no data_type); a
// term-valued leaf additionally pins an admissible set — `values` (each an ontology
// term NodeRef) or an ontology subtree (ontology + root_node). `subject_defining`
// flags the kind-defining rows (the D9 ingest invariant). Shape is intentionally
// open; the browser renders whatever columns are present.
export interface Binding {
  variable?: NodeRef;
  method?: NodeRef;
  class?: string;
  values?: Array<NodeRef | string>;
  ontology?: string;
  root_node?: string;
  subject_defining?: boolean;
  notes?: string;
  [k: string]: unknown;
}

// A D6 relation binding: the admissible value on directed_relation.relation /
// undirected_relation.relation, pinned to its carrier `class` with typed endpoints.
// `relation` is a {node, name} NodeRef (same shape as a binding's variable/method).
// A directed_relation carries child_types/parent_types (matching the schema
// child/parent deps); an undirected_relation carries a symmetric member_types
// (reserved — no undirected term exists yet).
export interface RelationTerm {
  relation: NodeRef;
  class: string; // "directed_relation" | "undirected_relation"
  child_role?: string;
  parent_role?: string;
  child_types?: string[];
  parent_types?: string[];
  member_types?: string[];
  ordered?: boolean;
  timed?: boolean;
  [k: string]: unknown;
}

export interface BindingRegistryMeta {
  title?: string;
  description?: string;
  subject_statement_bindings?: Binding[];
  binding_examples?: Binding[];
  relation_bindings?: RelationTerm[];
  notes?: string;
  [k: string]: unknown;
}

// Inside a schema file, `superclasses` is an array of objects with at least
// a `class_name` key. The repo-level index.json normalizes these to plain
// strings, so callers may see either shape -- always pass through
// `superclassName()` to extract the string.
export type SuperclassRef = string | { class_name: string; [k: string]: unknown };

export function superclassName(ref: SuperclassRef): string {
  return typeof ref === "string" ? ref : ref.class_name;
}
