export type Tier = "stable" | "draft" | "deprecated";
export type Maturity = "stable" | "draft" | "deprecated" | null;
// Migration disposition (written into index.json by build_v_eta.py):
//   persist     — settled go-forward class (in the final V1 set)
//   retire      — decided to dissolve/delete; not in final V1 (see disposition_note)
//   in_progress — persists but its ⑥/⑦ disposition is not yet finalized
export type Disposition = "persist" | "retire" | "in_progress";

export interface IndexEntry {
  class_name: string;
  tier: Tier;
  class_version: string | null;
  maturity_level: Maturity;
  superclasses: string[];
  path: string;
  is_meta?: boolean;
  disposition?: Disposition;
  disposition_note?: string;
}

export interface SchemaIndex {
  set_version: string;
  schema_version_value: string;
  based_on?: string;
  tiers: Tier[];
  notes?: string;
  schemas: IndexEntry[];
}

// Manifest of the schema sets available to the viewer, written by
// scripts/sync-schemas.mjs. `default` is the set shown on first load.
export interface VersionsManifest {
  versions: string[];
  default: string;
}

// V_eta migration coverage ledger (generated by tools/coverage.py, served as
// public/coverage.json). One row per did_v1 SOURCE class with its V_eta fate.
export interface CoverageRow {
  v1_class: string;
  veta_class: string | null; // null => no same-name V_eta class (dissolved/unmapped)
  disposition: string; // persist | retire | in_progress | a dissolved/unmapped label
  migrator: boolean; // a bespoke migrator consumes it (else base/passthrough)
  source: "ndi" | "app"; // NDI production template vs vhlab app/calculator class
  nonprod: boolean; // NDI test/demo scaffolding, not real corpus data
  gap: boolean; // no V_eta home, no migrator, never reviewed -> actionable hole
  // Migration TARGETS: the V_eta document class(es) the migrator emits.
  targets: string[]; // pass-1 emitted classes (or [same-name] when passthrough)
  // WHERE `targets` CAME FROM. Three different claims that used to render the
  // same way: "emitted" is measured from the migrators; "passthrough" means no
  // migrator exists and the document lands on the same-name class, which is
  // NOT a statement about where the class is going; "unknown" means neither.
  // "uncurated" is the actionable one: a migrator DOES run, but nothing
  // records what it emits -- a missing row in V_eta_migration_targets.json.
  // `decided` added 2026-08-10: the disposition is signed but NO migrator emits
  // it yet, so `targets` is empty and `decided_targets` carries what it WILL
  // become. Keeping them in separate fields is deliberate -- the ledger must
  // never let a decided target read as a produced one.
  target_source: "emitted" | "decided" | "uncurated" | "passthrough" | "unknown";
  decided_targets: string[]; // signed destination; nothing emits it yet
  carried: string[]; // pre-existing classes the emitted statements attach to (not minted)
  second_pass: string[]; // classes minted in the NDI second pass
  how: string; // one-line authored intent
  target_flags: string; // caveats: dynamic emit, header/code mismatch, deferrals
  // BUILD STATE -- computed by tools/coverage.py, committed in the ledger, and
  // rendered by NOTHING until the class-detail view: 0 occurrences of
  // `build_state` in this app before 2026-08-12. It splits a question the
  // `fate` badge runs together -- is the SCHEMA there, and does a MIGRATOR
  // emit it -- which were true of different halves for different classes.
  build_state?: BuildState;
  // A signed decision names targets; `decided_targets_source` says where that
  // naming came from and `decided_signoff` is the signature line itself. Both
  // were in the ledger and neither reached a reader.
  decided_targets_source?: string | null;
  decided_signoff?: string | null;
  no_target_reason?: string | null;
  no_target_account?: string | null;
  no_target_signoff?: string | null;
  // NARROWER than the retired `gap`: no target AND no dissolution recorded --
  // a gap, not a decision. Also rendered by nothing until now.
  target_gap?: boolean;
  // A DERIVED MIGRATION STAGE (a 0-5 ladder) is being added to the ledger by
  // another generator. It is typed permissively and rendered only if present,
  // because guessing its shape and rendering a wrong ladder would be worse
  // than rendering none: this viewer must not invent a field's meaning. A bare
  // number, or an object carrying a level and a label, are both understood;
  // anything else is shown as raw JSON rather than silently dropped.
  stage?: number | Record<string, unknown> | null;
  // WHY an empty `decided_targets` is empty. Four causes, and they are not
  // interchangeable: a signed dissolution (no target IS the answer), a signed
  // passthrough, a DISPUTED row where the record states two incompatible
  // dispositions, and a genuine gap where nothing was ever recorded. The
  // viewer rendered all four as "it dissolves or is deleted" -- asserting a
  // decision on behalf of rows where none exists. Absent on older ledgers,
  // which must render as UNKNOWN rather than falling back to the old claim.
  no_target_reason_label?: string | null;
}

// `build_state`, in full. Two independent halves, deliberately not summed into
// a single "done" flag: `schema_targets_built` is about this repository and
// `migrator_emits_decided_targets` is about DID-matlab, and for several classes
// exactly one of them is true.
export interface BuildState {
  schema_targets_named: number;
  schema_targets_built: string[];
  schema_targets_missing: string[];
  migrator_emits_decided_targets: boolean;
  has_per_class_migrator: boolean;
}

// ---- The per-class walkthrough asset (web/public/class_walkthrough.json,
// generated by tools/gen_class_walkthrough.py) -----------------------------
//
// What the ledger cannot say: what NDI actually declares for a v1 class, and
// which files in DID-matlab name it. Committed rather than synced, because the
// deploy workflow runs `npm ci && npm run build` and has no Python.
export interface NdiDeclaration {
  fields?: string[];
  raw_fields?: string[];
  depends_on?: string[];
  depends_on_required?: Record<string, boolean>;
  files?: string[];
  superclasses?: string[];
  path?: string;
  schema_document_form?: string;
  [k: string]: unknown;
}

export interface MigratorFile {
  package: string;
  spelling: string;
  path: string;
}

export interface ConvertMention {
  pass: string;
  path: string;
  site_count: number;
  sites: Array<{ line: number; spelling: string; text: string }>;
}

export interface WalkthroughClass {
  ndi: NdiDeclaration | null;
  ndi_absent_reason: string | null;
  writer_divergence: Array<Record<string, string>>;
  v_alpha_divergence: {
    only_in_our_snapshot?: string[];
    only_in_ndi_template?: string[];
    provenance?: { verdict?: string; why?: string };
  } | null;
  migrator_reads: Array<{
    migrator?: string;
    confidence?: string;
    reads_names_absent_from_template?: string[];
    mentions_names_absent_from_template?: string[];
  }>;
  consumers: {
    per_class_migrators: MigratorFile[];
    convert_package_mentions: ConvertMention[];
  };
}

export interface WalkthroughDoc {
  title: string;
  description: string;
  generated_by: string;
  sources: Record<string, string | null>;
  denominator: {
    ledger_rows_read: number;
    ndi_ground_truth_classes: number;
    rows_with_an_ndi_declaration: number;
    rows_without_one: number;
    convert_package_files_scanned: number;
    rows_with_a_per_class_migrator_file: number;
    did_matlab_available: boolean;
    ledger_disagreements: unknown[];
    [k: string]: unknown;
  };
  classes: Record<string, WalkthroughClass>;
}

// ---- The tenet map (web/public/tenets.json, generated by tools/tenet_map.py)
export interface TenetStatement {
  id: string;
  title: string;
  statement: string;
  line: number;
}

export interface TenetRow {
  tenet: string;
  change: string;
  before: string[];
  after: string[];
  after_built: string[];
  after_not_built: string[];
  plan_only_classes: string[];
  class_registers: Record<string, string[]>;
  citation: { doc: string; line: number; anchor: string; quote: string };
  note: string;
}

export interface TenetsDoc {
  title: string;
  description: string;
  tenets_document: string;
  denominator: {
    tenets_declared: number;
    tenets_with_at_least_one_row: number;
    tenets_with_no_substantiated_row: string[];
    rows: number;
    distinct_classes_named: number;
    classes_in_the_built_set: number;
    classes_that_are_v1_sources: number;
    classes_vouched_only_by_the_cited_plan: string[];
    plan_documents_cited: string[];
    negative_control: string;
  };
  tenets: TenetStatement[];
  rows: TenetRow[];
  classes_index: string[];
}

export interface CoverageSummary {
  total: number;
  by_disposition: Record<string, number>;
  by_source: Record<string, number>;
  with_migrator: number;
  gaps: number;
}

export interface CoverageLedger {
  title: string;
  description: string;
  summary: CoverageSummary;
  rows: CoverageRow[];
}

// ---- Decision families (schemas/V_eta_decisions.json, generated by
// tools/status_board.py) --------------------------------------------------
//
// The ledger says what a class's DISPOSITION is; this says whether the model
// behind it has been DECIDED. Those are different facts, and the viewer showed
// only the first: a signed, settled family whose build is queued rendered as
// `in_progress`, which reads as "nobody has decided this yet".
export type DecisionState =
  | "signed_awaiting_build"
  | "awaiting_signature"
  | "proposed_unreviewed"
  | "open";

export interface DecisionMember {
  class_name: string;
  disposition: string; // the class's own state; may already be built
}

export interface DecisionFamily {
  name: string;
  members: DecisionMember[];
  open_members: string[];
  plan: string | null;
  decision: string;
  status: "team" | "proposed" | "open";
  signed: boolean;
  signoff: string | null;
  state: DecisionState;
  state_label: string;
}

export interface DecisionsDoc {
  title: string;
  description: string;
  summary: {
    families: number;
    classes_claimed: number;
    open_classes: number;
    by_state: Record<DecisionState, number>;
    state_labels: Record<DecisionState, string>;
  };
  families: DecisionFamily[];
  by_class: Record<string, string>; // class name -> family name
}

// Topic tree (purely a viewer affordance). Lives in
// schemas/V_delta/topics.json. Interior nodes have a `name`; leaves are
// referenced by class_name in `classes`. Children may be omitted.
export interface TopicCategory {
  name: string;
  description?: string;
  classes?: string[];
  children?: TopicCategory[];
}

export interface TopicsFile {
  set_version: string;
  notes?: string;
  // Top-level bare leaf classes (rendered without a folder at the root of
  // the topic tree). Example: `base`.
  classes?: string[];
  topics: TopicCategory[];
}

export interface FieldDef {
  name: string;
  type: string;
  blank_value?: unknown;
  default_value?: unknown;
  mustBeNonEmpty?: boolean;
  mustBeScalar?: boolean;
  mustNotHaveNaN?: boolean;
  queryable?: boolean;
  ontology?: { node?: string; name?: string } | null;
  documentation?: string;
  constraints?: Record<string, unknown> | null;
  fields?: FieldDef[];
}

export interface DependsOnEntry {
  name: string;
  mustBeNonEmpty?: boolean;
  documentation?: string;
}

export interface FileEntry {
  name: string;
  documentation?: string;
}

export interface SchemaDocument {
  document_class?: {
    class_name: string;
    class_version?: string;
    superclasses?: SuperclassRef[];
    maturity_level?: Maturity;
  };
  depends_on?: DependsOnEntry[];
  file?: FileEntry[];
  fields?: FieldDef[];
  // Meta-schemas and registries may have arbitrary other shapes; keep open.
  [key: string]: unknown;
}

// The binding registry meta-file (schemas/V_*/stable/binding_registry_meta.json).
// Maps a statement's `variable` to the admissible value_set for its term value,
// and declares the kind-defining variables whose presence marks a subject's kind
// (D9). Only present from V_eta on; absent sets simply have no registry to browse.
// An ontology node reference: a CURIE plus a human-readable label snapshot.
export interface NodeRef {
  node: string;
  name: string;
}

// A subject_statement binding: variable (+ method) -> the concrete leaf `class`
// that carries the statement. The leaf fixes the value type (no data_type); a
// term-valued leaf additionally pins an admissible set — `values` (each an ontology
// term NodeRef) or an ontology subtree (ontology + root_node). `subject_defining`
// flags the kind-defining rows (the D9 ingest invariant). Shape is intentionally
// open; the browser renders whatever columns are present.
export interface Binding {
  variable?: NodeRef;
  method?: NodeRef;
  class?: string;
  values?: Array<NodeRef | string>;
  ontology?: string;
  root_node?: string;
  subject_defining?: boolean;
  notes?: string;
  [k: string]: unknown;
}

// A D6 relation binding: the admissible value on directed_relation.relation /
// undirected_relation.relation, pinned to its carrier `class` with typed endpoints.
// `relation` is a {node, name} NodeRef (same shape as a binding's variable/method).
// A directed_relation carries child_types/parent_types (matching the schema
// child/parent deps); an undirected_relation carries a symmetric member_types
// (reserved — no undirected term exists yet).
export interface RelationTerm {
  relation: NodeRef;
  class: string; // "directed_relation" | "undirected_relation"
  child_role?: string;
  parent_role?: string;
  child_types?: string[];
  parent_types?: string[];
  member_types?: string[];
  ordered?: boolean;
  timed?: boolean;
  [k: string]: unknown;
}

export interface BindingRegistryMeta {
  title?: string;
  description?: string;
  subject_statement_bindings?: Binding[];
  binding_examples?: Binding[];
  relation_bindings?: RelationTerm[];
  notes?: string;
  [k: string]: unknown;
}

// Inside a schema file, `superclasses` is an array of objects with at least
// a `class_name` key. The repo-level index.json normalizes these to plain
// strings, so callers may see either shape -- always pass through
// `superclassName()` to extract the string.
export type SuperclassRef = string | { class_name: string; [k: string]: unknown };

export function superclassName(ref: SuperclassRef): string {
  return typeof ref === "string" ? ref : ref.class_name;
}
